// src/app/components/ProductItem/index.tsx
/**
 *
 * ProductItem
 *
 */
import React, { memo, useCallback } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { ProductItemStyle } from 'styles/product-item-styles';
import { slice } from 'app/components/MyCart/slice';
import { selectMyCart } from 'app/components/MyCart/selectors';

interface Props {
  id: string;
  name: string;
  imageURL: string;
  description: string;
  price: number;
}

export const ProductItem = memo((props: Props) => {
  const dispatch = useDispatch();
  const cart = useSelector(selectMyCart);

  const { id, name, imageURL, description, price } = props;

  const addToCart = data => {
    const { actions } = slice;
    dispatch(
      actions.addItem({
        cart,
        newItem: data,
      }),
    );
  };

  return (
    <article className="product-item" key={id}>
      <div className="product-item-title">{name}</div>
      <div className="product-info">
        <div className="product-img">
          <img src={imageURL} alt="imagename" />
        </div>
        <div className="product-desc">{description}</div>
      </div>
      <div className="product-purchase">
        <div className="product-mrp">MRP Rs.{price}</div>
        <button
          className="product-btn-buynow"
          aria-label="Buy Now"
          onClick={() => addToCart(props)}
        >
          Buy Now
        </button>
        <button
          className="product-btn-small-screen"
          aria-label="Buy Now"
          onClick={() => addToCart(props)}
        >
          Buy Now @ Rs.{price}
        </button>
      </div>
      <ProductItemStyle />
    </article>
  );
});

// src/app/features/products/components/product-item/product-item.component.ts
import { Component, Input } from '@angular/core';
import { Store } from '@ngrx/store';
import { ICartItem } from 'src/app/shared/models/cart-item.model';
import { addProduct } from 'src/app/core/store/actions/cart.actions';
import { IProduct } from 'src/app/shared/models/product.model';

@Component({
  selector: 'app-product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.sass'],
})
export class ProductItemComponent {
  @Input() product!: IProduct;
  constructor(private store: Store<{ cartList: ICartItem[] }>) {}
  addToCart(item: IProduct) {
    const cartItem: ICartItem = {
      product: item,
      quantity: 1,
    };
    this.store.dispatch(addProduct(cartItem));
  }
}

<div *ngIf="product" class="product">
  <div class="container">
    <div class="title">
      {{ product.product.name }}
    </div>
    <div class="sub-container">
      <img
        [src]="'../../assets/' + product.product.imageURL"
        alt="product image"
      />
      <div class="right-container">
        <div class="desc-container">
          <div class="desc">
            <p [title]="product.product.description">
              {{ product.product.description }}
            </p>
          </div>
        </div>
        <button
          *ngIf="product.quantity == 0"
          (click)="addToCart(product)"
          class="buy-now mobile"
        >
          Buy Now @ Rs.{{ product.product.price }}
        </button>
        <div *ngIf="product.quantity > 0" class="mobile">
          <div class="quantity">
            <span (click)="minusQuantity(product)" class="minus circle">-</span>
            <span aria-label="product quantity added to cart" class="count">{{
              product.quantity
            }}</span>
            <span (click)="addToCart(product)" class="circle">+</span>
          </div>
        </div>
      </div>
    </div>
    <div class="product-footer tablet">
      <div class="price desktop">MRP Rs.{{ product.product.price }}</div>
      <div *ngIf="product.quantity > 0" class="desktop">
        <div class="quantity">
          <span (click)="minusQuantity(product)" class="minus circle">-</span>
          <span class="count">{{ product.quantity }}</span>
          <span (click)="addToCart(product)" class="circle">+</span>
        </div>
      </div>
      <button
        *ngIf="product.quantity == 0"
        (click)="addToCart(product)"
        class="buy-now desktop"
      >
        Buy Now
      </button>
      <button
        *ngIf="product.quantity === 0"
        (click)="addToCart(product)"
        class="buy-now tablet"
      >
        Buy Now @ Rs.{{ product.product.price }}
      </button>
      <div *ngIf="product.quantity > 0" class="tablet">
        <div class="quantity">
          <span (click)="minusQuantity(product)" class="minus circle">-</span>
          <span class="count">{{ product.quantity }}</span>
          <span (click)="addToCart(product)" class="circle">+</span>
        </div>
      </div>
    </div>
  </div>
</div>
