// client/src/components/products/ProductItem.tsx
import useAppStore from '../../utils/store/store';
import { Product } from '../../utils/types/product';

function ProductItem({ product }: { product: Product }) {
  const { addToCart } = useAppStore();
  return (
    <div className="product-item">
      <h2 className="product-name">{product.name}</h2>
      <div className="product-content-wrapper">
        <div className="product-image">
          <img src={product.imageURL} alt="Product" />
        </div>
        <div className="product-content">
          <div className="product-description">{product.description}</div>
        </div>
      </div>
      <div className="product-actions">
        <div className="product-price">MRP Rs.{product.price}</div>
        <button type="button" className="desktop-button" onClick={() => addToCart(product)}>
          Buy Now
        </button>
        <button type="button" className="responsive-button" onClick={() => addToCart(product)}>
          Buy Now @ Rs.{product.price}
        </button>
      </div>
    </div>
  );
}

export default ProductItem;

// src/app/features/products/components/product-item/product-item.component.ts
import { Component, Input } from '@angular/core';
import { Store } from '@ngrx/store';
import { ICartItem } from 'src/app/shared/models/cart-item.model';
import { addProduct } from 'src/app/core/store/actions/cart.actions';
import { IProduct } from 'src/app/shared/models/product.model';

@Component({
  selector: 'app-product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.sass'],
})
export class ProductItemComponent {
  @Input() product!: IProduct;
  constructor(private store: Store<{ cartList: ICartItem[] }>) {}
  addToCart(item: IProduct) {
    const cartItem: ICartItem = {
      product: item,
      quantity: 1,
    };
    this.store.dispatch(addProduct(cartItem));
  }
}

<div *ngIf="product" class="product">
  <div class="container">
    <div class="title">
      {{ product.product.name }}
    </div>
    <div class="sub-container">
      <img
        [src]="'../../assets/' + product.product.imageURL"
        alt="product image"
      />
      <div class="right-container">
        <div class="desc-container">
          <div class="desc">
            <p [title]="product.product.description">
              {{ product.product.description }}
            </p>
          </div>
        </div>
        <button
          *ngIf="product.quantity == 0"
          (click)="addToCart(product)"
          class="buy-now mobile"
        >
          Buy Now @ Rs.{{ product.product.price }}
        </button>
        <div *ngIf="product.quantity > 0" class="mobile">
          <div class="quantity">
            <span (click)="minusQuantity(product)" class="minus circle">-</span>
            <span aria-label="product quantity added to cart" class="count">{{
              product.quantity
            }}</span>
            <span (click)="addToCart(product)" class="circle">+</span>
          </div>
        </div>
      </div>
    </div>
    <div class="product-footer tablet">
      <div class="price desktop">MRP Rs.{{ product.product.price }}</div>
      <div *ngIf="product.quantity > 0" class="desktop">
        <div class="quantity">
          <span (click)="minusQuantity(product)" class="minus circle">-</span>
          <span class="count">{{ product.quantity }}</span>
          <span (click)="addToCart(product)" class="circle">+</span>
        </div>
      </div>
      <button
        *ngIf="product.quantity == 0"
        (click)="addToCart(product)"
        class="buy-now desktop"
      >
        Buy Now
      </button>
      <button
        *ngIf="product.quantity === 0"
        (click)="addToCart(product)"
        class="buy-now tablet"
      >
        Buy Now @ Rs.{{ product.product.price }}
      </button>
      <div *ngIf="product.quantity > 0" class="tablet">
        <div class="quantity">
          <span (click)="minusQuantity(product)" class="minus circle">-</span>
          <span class="count">{{ product.quantity }}</span>
          <span (click)="addToCart(product)" class="circle">+</span>
        </div>
      </div>
    </div>
  </div>
</div>
