// shopping-cart-client/src/app/products/product-card/product-card.component.ts
import { Component, HostListener, Input, OnInit } from '@angular/core';
import { Products } from '../../models/Products';
import { CartService } from '../../services/cart-services/cart.service';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.css'],
})
export class ProductCardComponent implements OnInit {
  @Input() product: Products;
  @Input() isDesktop: boolean;
  constructor(private cartService: CartService) {}

  ngOnInit(): void {}

  addItemToCart(id: string) {
    this.cartService.addItemToCart(id);
  }
}

<div class="product-card-cont">
  <h2 class="product-card-title">{{ product.name }}</h2>
  <img
    class="product-card-img"
    src="assets{{ product.imageURL }}"
    sizes="(min-width: 1024px) 40vw,
  (min-width: 768px) 50vw,
  50vw"
    [alt]="product.description"
    width="100%"
  />
  <div class="product-card-subtext">
    <p>{{ product.description }}</p>
  </div>
  <div class="product-buy">
    <span *ngIf="isDesktop" class="product-card-cost"
      >MRP Rs{{ product.price }}</span
    >
    <button
      [attr.data-price]="product.price"
      type="button"
      (click)="addItemToCart(product.id)"
      class="btn"
      role="button"
    >
      {{ isDesktop ? "Buy Now" : "Buy Now@" }}
      <span *ngIf="!isDesktop">{{ product.price }}</span>
    </button>
  </div>
</div>

// app/src/components/products/product-card.jsx
import { Card } from 'react-bootstrap';
import { addCart } from "../../store/actions/cart.action";
import { useDispatch } from "react-redux";

const ProductCard = ({ product }) => {
    const { name, imageURL, description, price } = product;
    const dispatch = useDispatch();
    const buyProduct = () => {
        dispatch(addCart(product))
    }
    return (
        <div className='product'>
            <Card >
                <div className='title'>{name}</div>
                <div className='card-data'>
                    <Card.Img variant="top" src={imageURL} alt={name} />
                    <Card.Body>
                        <Card.Text>
                            {description}
                        </Card.Text>
                        <div className='card-footer'>
                            <div className='price'>MRP Rs.{price}</div>
                            <button className='btn-cls' onClick={buyProduct}>Buy now</button>
                        </div> 
                    </Card.Body>
                </div>
            </Card>

        </div>
    );
}

export default ProductCard;
