// ClientSide/src/app/product-card/product-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Products } from '../models/Products';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.scss'],
})
export class ProductCardComponent implements OnInit {
  @Input() product: Products;
  constructor() {}

  ngOnInit(): void {}
}

<div class="product-card-cont">
  <h2 class="product-card-title">{{product.name}}</h2>
  <img class="product-card-img" [src]="product.imageURL" [alt]="product.description" width="100%">
  <div class="product-card-subtext">
    <p>{{product.description}}</p>
  </div>
  <div class="product-buy">
    <span class="product-card-cost">MRP Rs{{product.price}}</span>
    <button class="btn">Buy Now</button>
  </div>
</div>

// app/src/components/products/product-card.jsx
import { Card, Col, Row } from 'react-bootstrap';

const ProductCard = (props) => {
    const { products } = props;
    return (
        <div className='product'>
            <Row>
                {
                    products.map((item) => {
                        return (
                            <Col xs={6} md={4} key={item.id}>
                                <Card >
                                    <div className='title'>{item.name}</div>
                                    <Card.Img variant="top" src={item.imageURL} alt={item.name} />
                                    <Card.Body>
                                        <Card.Text>
                                           {item.description}
                                        </Card.Text>
                                        <div className='card-footer'>
                                        <div className='price'>MRP Rs{item.price}</div>
                                        <button className='btn-cls'>Buy now</button>
                                        </div>
                                    </Card.Body>
                                </Card>
                            </Col>
                        )
                    })
                }
            </Row>
        </div>
    );
}

export default ProductCard;
