// shopping-website/src/pages/Register.jsx
import { Formik } from "formik";
import React from "react";
import Input from "../components/form/Input";
import "./Register.scss";
import * as Yup from "yup";

const Register = () => {

    const passwordRegex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;

  const validations = Yup.object({
    firstName: Yup.string().required("First Name is Required"),
    lastName: Yup.string().required("Last Name is Required"),
    email: Yup.string()
      .required("Email is Required")
      .email("Invalid email address"),
    password: Yup.string()
      .required("password is required")
      .matches(
        passwordRegex,
        "password must contain one number,one letter,without spaces and minimum 6 characters long"
      ),
    confirmPassword: Yup.string().oneOf(
      [Yup.ref("password"), null],
      "Passwords must match"
    ),
  });

  return (
    <section className="registerContainer">
      <div className="registerDesc">
        <h1 style={{ fontWeight: "bold" }}>Signup</h1>
        <p className="registerHeading">
          We do not share your personal details with anyone
        </p>
      </div>
      <div className="registerForm">
        <Formik
          initialValues={{
            firstName: "",
            lastName: "",
            email: "",
            password: "",
            confirmPassword: "",
          }}
          validationSchema = {validations}
          onSubmit={(values) => {
              console.log('here');
            console.log(values);
          }}
        >
          {({
            values,
            touched,
            errors,
            handleChange,
            handleBlur,
            handleSubmit,
            isSubmitting,
          }) => (
            <form onSubmit={handleSubmit}>
              <Input
                type="text"
                name="firstName"
                label="First Name"
                placeholder="First Name"
                value={values.firstName}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.firstName && touched.firstName && errors.firstName}
              />
              <Input
                type="text"
                name="lastName"
                label="Last Name"
                placeholder="Last Name"
                value={values.lastName}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.lastName && touched.lastName && errors.lastName}
              />
              <Input
                type="email"
                name="email"
                label="Email"
                placeholder="Email"
                value={values.email}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.email && touched.email && errors.email}
              />
              <Input
                type="password"
                name="password"
                label="Password"
                placeholder="Password"
                value={values.password}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.password && touched.password && errors.password}
              />
              <Input
                type="password"
                name="confirmPassword"
                label="Confirm Password"
                placeholder="Confirm Password"
                value={values.confirmPassword}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.confirmPassword && touched.confirmPassword && errors.confirmPassword}
              />
              <button type="submit" className="submitButton">
          <p
            style={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "center",
            }}
          >
            Register
          </p>
        </button>
            </form>
          )}
        </Formik>
      </div>
    </section>
  );
};

export default Register;

// frontend/src/app/register/register-component/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss'],
})
export class RegisterComponent implements OnInit {
  registerForm: FormGroup = new FormGroup({});
  constructor(
    private fb: FormBuilder,
    private router: Router,
    private auth: AuthService
  ) {}

  ngOnInit(): void {
    this.createRegisterForm();
  }

  createRegisterForm() {
    this.registerForm = this.fb.group(
      {
        fName: ['', Validators.required],
        lName: ['', Validators.required],
        email: ['', Validators.required],
        password: ['', Validators.required],
        confirmPassword: ['', Validators.required],
      },
      {
        validator: this.mustMatch('password', 'confirmPassword'),
      }
    );
  }

  mustMatch(controlName: string, matchingControlName: string) {
    return (formGroup: FormGroup) => {
      const control = formGroup.controls[controlName];
      const matchingControl = formGroup.controls[matchingControlName];

      if (matchingControl.errors && !matchingControl.errors.mustMatch) {
        return;
      }

      if (control.value !== matchingControl.value) {
        matchingControl.setErrors({ mustMatch: true });
      } else {
        matchingControl.setErrors(null);
      }
    };
  }

  get formControl() {
    return this.registerForm.controls;
  }

  onSubmit(): void {
    this.auth.signedIn(this.registerForm.controls['email'].value);
    this.router.navigate(['/login']);
  }
}

<app-header></app-header>

<section class="signup-container">
  <div class="text-container">
    <p class="signup-header">Signup</p>
    <p class="signup-desc">
      We do not share your personal details with anyone.
    </p>
  </div>

  <div class="form-container">
    <div class="form" [formGroup]="registerForm">
      <label for="fName"> First Name</label>
      <input type="text" formControlName="fName" name="fName" />

      <div
        *ngIf="
          formControl.fName.invalid &&
          (formControl.fName.dirty || formControl.fName.touched)
        "
      >
        <p *ngIf="formControl.fName.errors?.required" class="has-error">
          First name is required.
        </p>
      </div>
      <label for="lName"> Last Name</label>
      <input type="text" formControlName="lName" name="lName" />
      <div
        *ngIf="
          formControl.lName.invalid &&
          (formControl.lName.dirty || formControl.lName.touched)
        "
      >
        <div *ngIf="formControl.lName.errors?.required" class="has-error">
          Last name is required.
        </div>
      </div>

      <label for="email"> Email</label>
      <input type="email" formControlName="email" name="email" />
      <div
        *ngIf="
          formControl.email.invalid &&
          (formControl.email.dirty || formControl.email.touched)
        "
      >
        <div *ngIf="formControl.email.errors?.required" class="has-error">
          Email is required.
        </div>
      </div>

      <label for="password"> Password </label>
      <input type="password" formControlName="password" name="password" />
      <div
        *ngIf="
          formControl.password.invalid &&
          (formControl.password.dirty || formControl.password.touched)
        "
      >
        <div *ngIf="formControl.password.errors?.required" class="has-error">
          Password is required.
        </div>
      </div>

      <label for="cPassword"> Confirm Password</label>
      <input
        type="password"
        formControlName="confirmPassword"
        name="cPassword"
      />
      <div
        *ngIf="
          formControl.confirmPassword.invalid &&
          (formControl.confirmPassword.dirty ||
            formControl.confirmPassword.touched)
        "
      >
        <div
          *ngIf="formControl.confirmPassword.errors?.required"
          class="has-error"
        >
          Confirm Password is required.
        </div>
        <div
          *ngIf="formControl.confirmPassword.errors?.mustMatch"
          class="has-error"
        >
          Passwords must match
        </div>
      </div>

      <button type="submit" (click)="onSubmit()">Register</button>
    </div>
  </div>
</section>
