// src/app/cart/components/cart-offer/cart-offer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'cart-offer',
  templateUrl: './cart-offer.component.html',
  styleUrls: ['./cart-offer.component.scss']
})
export class CartOfferComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<!-- Offer section -->
<div class="offer margin-top-10 clearfix">
    <figure class="pull-left"><img src="../../../../assets/images/lowest-price.png" alt="Lowest Price logo"></figure>
    <p class="disp-inline margin-left-20">You won't find it cheaper anywhere.</p>
</div>

// src/components/cart/CartOffer.jsx
import React from "react";
import offerImg from "../../static/images/lowest-price.png";

const CartOffer = () => {
  return (
    <>
      <div className="cart-offer">
        <div className="container-fluid p-0">
          <div className="row">
            <div className="col-4">
              <img
                src={offerImg}
                alt="lowest price"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="col-8 align-items-center d-flex">
              <span className="d-block text-left">
                You won't find it cheaper anywhere
              </span>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default CartOffer;
