// src/components/Cart/Cart.jsx
import React, { useEffect } from "react";
import styles from "./Cart.module.scss";
import { createPortal } from "react-dom";
import Button from "@components/Button";


class Modal extends React.Component {
    constructor(props) {
        super(props);
        this.el = document.createElement("div");
        this.modalRootEl = document.createElement("div");
        document.body.appendChild(this.modalRootEl);
    }

    componentDidUpdate() {
        if (this.props.isOpen) {
            document.body.style.overflow="hidden";
        } else {
            document.body.style.overflow="auto";
        }
    }

    componentDidMount() {
        this.modalRootEl.appendChild(this.el);
    }

    componentWillUnmount() {
        this.modalRootEl.removeChild(this.el);
    }

    render() {
        return this.props.isOpen ? createPortal(
            <div className={styles.modal}>
                <div className={styles.overlay} onClick={this.props.onClose}></div>
                <div className={styles.modalContent}>
                    {this.props.children}
                </div>
            </div>,
            this.el,
        ) : null;
    }
}

export function Cart(props) {
    const { onClose, items, totalPrice, totalItems, onAdd, onRemove } = props;

    return (
        <div className={styles.cartWrapper}>
            <div className={styles.cartHead}>
                <h1 className={styles.cartTitle} data-testid="cart-title">My Cart ({totalItems} items)</h1>
                <button className={styles.close} onClick={onClose} data-testid="cart-close">✕</button>
            </div>
            {
                !items.length ? <>
                    <div className={styles.cartBody} data-testid="cart-empty">
                        <section className={styles.emptyCart}>
                            <div className={styles.emptyCartMessage}>
                                <h2 className={styles.emptyCartTitle} data-testid="cart-empty-title">No items in your cart</h2>
                                <p className={styles.emptyCartDescription}>Your favourite items are just a click away</p>
                            </div>
                            <div className={styles.startShopping}>
                                <Button className={styles.startShoppingButton}>Start Shopping</Button>
                            </div>
                        </section>
                    </div>
                </> : null
            }
            {
                items.length ? <>
                    <div className={styles.cartBody}>
                        <div className={styles.cartItems}>
                            {
                                items.map((cartItem) => (
                                    <div className={styles.cartItem} key={cartItem.id} data-testid="cart-item">
                                        <img src={cartItem.imageURL} className={styles.productImage} alt={cartItem.name} />
                                        <div className={styles.productWrapper}>
                                            <h2 className={styles.productsName} data-testid="product-name">{cartItem.name}</h2>
                                            <div className={styles.productCounterWrapper}>
                                                <div className={styles.productCounter}>
                                                    <button className={styles.productCounterButton}
                                                        onClick={() => onRemove(cartItem)} data-testid="product-remove">-</button>
                                                    <p className={styles.productPrice}>{cartItem.count}</p>
                                                    <button className={styles.productCounterButton}
                                                        onClick={() => onAdd(cartItem)} data-testid="product-add"
                                                        disabled={cartItem.count === cartItem.stock}
                                                    >+</button>
                                                    <p className={styles.multiply}>✕</p>
                                                    <p className={styles.productPrice}>{cartItem.price}</p>
                                                </div>
                                                <p className={styles.totalPrice}>Rs.{cartItem.price * cartItem.count}</p>
                                            </div>
                                        </div>
                                    </div>
                                ))
                            }
                            <div className={styles.cartDiscount}>
                                <img src="/static/images/lowest-price.png" className={styles.discountImage} alt="Discounted Image" />
                                <p className={styles.discountText}>You won't find it cheaper anywhere</p>
                            </div>
                        </div>
                        <div className={styles.checkoutWrapper}>
                            <p className={styles.text}>Promo code can be applied on payment page</p>
                            <Button className={styles.checkoutButton}>
                                <span>Proceed to Checkout</span>
                                <span>Rs.{totalPrice} ❯</span>
                            </Button>
                        </div>
                    </div>
                </> : null
            }
        </div>
    );
}

export function CartModal(props) {

    const { isOpen, onClose, items, totalPrice, totalItems, onAdd, onRemove } = props;

    return (
        <Modal isOpen={isOpen} onClose={onClose}>
            <div className={styles.cartModal}>
                <Cart
                    items={items}
                    onClose={onClose}
                    totalItems={totalItems}
                    onAdd={onAdd}
                    onRemove={onRemove}
                    totalPrice={totalPrice}
                />
            </div>
        </Modal>
    );
}

// src/app/shared/component/cart/cart.component.ts
import { Component, Inject, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ModalDismissReasons, NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { CartService } from '../../services/cart/cart.service';
import { EmptyCartComponent } from '../empty-cart/empty-cart.component';
@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss'],
})
export class CartComponent implements OnInit {
  closeModal: string;

  cart: any = 'ad';
  cartList: any = [];
  constructor(
    private modalService: NgbModal,
    private _cartService: CartService,
    private _modalService: NgbModal,
    private _route: Router
  ) {}
  ngOnInit(): void {
    this.getCartList();
  }

  getCartList() {
    this._cartService.getCartList.subscribe((data) => {
      this.cartList = data;
      if (this.cartList.length == 0) {
        this._modalService.open(EmptyCartComponent, {
          ariaLabelledBy: 'cartTitle',
        });
      }
    });
  }

  addProductsToCart(product) {
    this._cartService.addProductToCart(product);
  }

  removeProductFromCart(product) {
    this._cartService.removeProductsFromCart(product);
  }

  startShopping() {
    this._route.navigate(['/home']);
  }
  resetCart() {}
}

<!-- <div class="o">
<h1> pooja</h1>
</div> -->

<div class="modal-header" role="dialog" aria-labelledby="cartTitle">
    <p class="modal-title" id="cartTitle">My Cart
        <span *ngIf="cartList.length >0">({{cartList.length}} item)</span>
    </p>
    <button class="close" aria-label="Close" (click)="resetCart();modal.dismiss('Cross click')"
        aria-label="Close Cart Popup">&times;</button>
</div>

<div class="modal-body" *ngIf="!cartList.length; else displayItems">
    <div class="cart-body">
        <p class="no-items main-heading" aria-level="1" role="heading">No items in your cart</p>
        <p>You favourite items are just a click away</p>
    </div>
</div>

<ng-template #displayItems>
    <div class="card mb-3">
        <div class="row no-gutters" *ngFor="let product of cartList; let i = index">
            <div class="col-md-2 col-sm-4 cart-image">
                <img src="assets/{{product.imageURL}}" class="card-img" alt="{{product.name}}" title="{{product.name}}">
            </div>
            <div class="col-md-10 col-sm-8 cart-description">
                <div class="card-body">
                    <p class="card-title" aria-level="1" role="heading">{{product.name}}</p>
                    <div>
                        <button (click)="removeProductFromCart(product)" class="card-btn">-</button>
                        <!-- <i class="fa fa-plus-square icon-fa" (click)="addProductsToCart(product)"
                            aria-label="increase product unit"></i> -->
                        <span>{{product.count}}</span>
                        <button (click)="addProductsToCart(product)" class="card-btn">+</button>
                        <!-- <i class="fa fa-minus-square icon-fa" (click)="removeProductFromCart(product)"
                            aria-label="decrease product unit"></i> -->
                        <span class="item-price">X &nbsp; &nbsp;{{product.price | currency: 'INR'}}</span>
                        <span class="item-total-price">{{product.productPrice | currency: 'INR'}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="cart-offer">
        <figure class="offer-img">
            <img class="offer-image" src="assets/static/images/lowest-price.png" alt="lowest-price" />
        </figure>
        <p class="offer-text">You won't find it cheaper anywhere</p>
    </div>
</ng-template>

<div class="modal-footer">
    <section *ngIf="!cartList.length; else checkout" class="footer-section">
        <button type="button" class="common-btn" data-dismiss="modal" (click)="resetCart();modal.close('Save click')"
            aria-label="Start Shopping">Start
            Shopping</button>
    </section>
    <ng-template #checkout>
        <p>Promo code can be applied on payment page</p>
        <button type="button" class="common-btn" (click)="resetCart();modal.close('Save click')" data-dismiss="modal"
            aria-label="Proceed to Checkout Rs.  /-">
            <span class="checkout-text">Proceed to Checkout </span>
             <span class="checkout-price">Rs.{{ cartList.totalAmount}}/- ></span>
        </button>
    </ng-template>
</div>
