// src/components/Cart/Cart.jsx
import React, { useEffect } from "react";
import styles from "./Cart.module.scss";
import { createPortal } from "react-dom";
import Button from "@components/Button";


class Modal extends React.Component {
    constructor(props) {
        super(props);
        this.el = document.createElement("div");
        this.modalRootEl = document.createElement("div");
        document.body.appendChild(this.modalRootEl);
    }

    componentDidUpdate() {
        if (this.props.isOpen) {
            document.body.style.overflow="hidden";
        } else {
            document.body.style.overflow="auto";
        }
    }

    componentDidMount() {
        this.modalRootEl.appendChild(this.el);
    }

    componentWillUnmount() {
        this.modalRootEl.removeChild(this.el);
    }

    render() {
        return this.props.isOpen ? createPortal(
            <div className={styles.modal}>
                <div className={styles.overlay} onClick={this.props.onClose}></div>
                <div className={styles.modalContent}>
                    {this.props.children}
                </div>
            </div>,
            this.el,
        ) : null;
    }
}

export function Cart(props) {
    const { onClose, items, totalPrice, totalItems, onAdd, onRemove } = props;

    return (
        <div className={styles.cartWrapper}>
            <div className={styles.cartHead}>
                <h1 className={styles.cartTitle} data-testid="cart-title">My Cart ({totalItems} items)</h1>
                <button className={styles.close} onClick={onClose} data-testid="cart-close">✕</button>
            </div>
            {
                !items.length ? <>
                    <div className={styles.cartBody} data-testid="cart-empty">
                        <section className={styles.emptyCart}>
                            <div className={styles.emptyCartMessage}>
                                <h2 className={styles.emptyCartTitle} data-testid="cart-empty-title">No items in your cart</h2>
                                <p className={styles.emptyCartDescription}>Your favourite items are just a click away</p>
                            </div>
                            <div className={styles.startShopping}>
                                <Button className={styles.startShoppingButton}>Start Shopping</Button>
                            </div>
                        </section>
                    </div>
                </> : null
            }
            {
                items.length ? <>
                    <div className={styles.cartBody}>
                        <div className={styles.cartItems}>
                            {
                                items.map((cartItem) => (
                                    <div className={styles.cartItem} key={cartItem.id} data-testid="cart-item">
                                        <img src={cartItem.imageURL} className={styles.productImage} alt={cartItem.name} />
                                        <div className={styles.productWrapper}>
                                            <h2 className={styles.productsName} data-testid="product-name">{cartItem.name}</h2>
                                            <div className={styles.productCounterWrapper}>
                                                <div className={styles.productCounter}>
                                                    <button className={styles.productCounterButton}
                                                        onClick={() => onRemove(cartItem)} data-testid="product-remove">-</button>
                                                    <p className={styles.productPrice}>{cartItem.count}</p>
                                                    <button className={styles.productCounterButton}
                                                        onClick={() => onAdd(cartItem)} data-testid="product-add"
                                                        disabled={cartItem.count === cartItem.stock}
                                                    >+</button>
                                                    <p className={styles.multiply}>✕</p>
                                                    <p className={styles.productPrice}>{cartItem.price}</p>
                                                </div>
                                                <p className={styles.totalPrice}>Rs.{cartItem.price * cartItem.count}</p>
                                            </div>
                                        </div>
                                    </div>
                                ))
                            }
                            <div className={styles.cartDiscount}>
                                <img src="/static/images/lowest-price.png" className={styles.discountImage} alt="Discounted Image" />
                                <p className={styles.discountText}>You won't find it cheaper anywhere</p>
                            </div>
                        </div>
                        <div className={styles.checkoutWrapper}>
                            <p className={styles.text}>Promo code can be applied on payment page</p>
                            <Button className={styles.checkoutButton}>
                                <span>Proceed to Checkout</span>
                                <span>Rs.{totalPrice} ❯</span>
                            </Button>
                        </div>
                    </div>
                </> : null
            }
        </div>
    );
}

export function CartModal(props) {

    const { isOpen, onClose, items, totalPrice, totalItems, onAdd, onRemove } = props;

    return (
        <Modal isOpen={isOpen} onClose={onClose}>
            <div className={styles.cartModal}>
                <Cart
                    items={items}
                    onClose={onClose}
                    totalItems={totalItems}
                    onAdd={onAdd}
                    onRemove={onRemove}
                    totalPrice={totalPrice}
                />
            </div>
        </Modal>
    );
}

// ClientSide/src/app/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { CartProducts } from '../models/CartProducts';
import { CartService } from '../shared/services/cart.service';
import { HomeService } from '../shared/services/home.service';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss'],
})
export class CartComponent implements OnInit {
  showModal: boolean;
  productsInCart: CartProducts[];
  checkoutAmont: number;

  constructor(private cartService: CartService) {}

  ngOnInit(): void {
    this.cartService.showCart.subscribe((data) => {
      this.showModal = data;
    });

    this.cartService.getCartItem.subscribe((data) => {
      this.productsInCart = data;
      this.checkoutAmont = this.productsInCart.reduce(
        (previousVal, currentVal) =>
          previousVal + (currentVal.price * currentVal.count),
        0
      );
    });
  }

  modifyItem(count: number, productId: string) {
    this.cartService.modifyItem(count, productId);
  }

  onClose() {
    // showModal = !showModal;
    this.cartService.hide();
  }
}

<div id="myModal" class="modal" [attr.data-show]="showModal">
  <div
    [attr.data-empty-cart]="productsInCart.length ? false : true"
    class="modal-content"
  >
    <div class="modal-header">
      <h2>My cart</h2>
      <!-- Modal content -->
      <button
        type="button"
        (click)="onClose()"
        aria-label="Close cart"
        class="close"
      >
      <i class="fa fa-times" aria-hidden="true"></i>
    </button>
    </div>
    <ng-container
      *ngTemplateOutlet="productsInCart.length ? itemsList : emptyCart"
    ></ng-container>
  </div>
  <ng-template #itemsList>
    <ul *ngIf="productsInCart.length" class="cart-items-warapper">
      <li *ngFor="let product of productsInCart">
        <div class="cart-item-image">
          <img
            class="product-card-img"
            [src]="product.imageURL"
            [alt]="product.description"
            width="100%"
          />
        </div>
        <div class="cart-item-desc">
          <div class="cart-item-title">{{ product.name }}</div>
          <button
            class="btn"
            aria-label="Increase By 1"
            (click)="modifyItem(1, product.id)"
          >
            <i class="fa fa-plus" aria-hidden="true"></i>
          </button>
          <span>{{ product.count }}</span>
          <button
            class="btn"
            aria-label="Decrease By 1"
            (click)="modifyItem(-1, product.id)"
          >
            <i class="fa fa-minus" aria-hidden="true"></i>
          </button>
          <span class="cart-item-price">X Rs.{{ product.price }}</span>
        </div>
        <div class="cart-item-total">Rs{{ product.price * product.count }}</div>
      </li>
      <li class="cart-footer-banner">
        <img
          src="static/images/lowest-price.png"
          alt=" "
          aria-labelledby="banner-tex"
        />
        <span id="banner-tex">You won't find it cheaper anywhere</span>
      </li>
    </ul>
    <div class="cart-payment-footer">
      <div class="promo-text">Promo can be applied Home Page</div>
      <div class="cart-payment-checkout">
        <button (click)="onClose()" class="btn">
          <span>Proceed to Checkout</span>
          <span>Rs. {{ checkoutAmont }} ></span>
        </button>
      </div>
    </div>
  </ng-template>
  <ng-template #emptyCart>
    <div class="empty-cart-wrapper">
      <div class="empty-cart-text">
        <h2>No items in your cart</h2>
        <p>Your favorite items are just a click away</p>
      </div>
      <div class="empty-cart-button">
        <button (click)="onClose()" class="btn">Start Shopping</button>
      </div>
    </div>
  </ng-template>
</div>
