// src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {
  registerForm: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group({
      firstName: ['', [Validators.required, Validators.minLength(4)]],
      lastName: ['', [Validators.required, Validators.minLength(4)]],
      email: ['', [Validators.required]],
      password: ['', [Validators.required]],
      confirmPassword: ['', [Validators.required]]
    }, { validator: this.matchPassword });
  }

  onSubmit() {
    this.router.navigate(['/home']);
  }

  matchPassword(abs: AbstractControl): { mismatch: boolean } {
    if (abs.get('password').value !== abs.get('confirmPassword').value) {
      return { mismatch: true };
    }
  }

}

<div class="container my-5">
    <section class="row">
        <div class="col-lg-6">
            <h2>Signup</h2>
            <p>We do not share your personal details with anyone.</p>
        </div>

        <div class="col-lg-6">
            <form [formGroup]="registerForm" novalidate (ngSubmit)="onSubmit()">
                <div class="form-group custom-group">
                    <input type="text" id="firstName" class="form-control" formControlName="firstName" placeholder=""
                        required aria-label="Enter firstName">
                    <label for="firstName" class="floating-label">First Name</label>

                    <div *ngIf="registerForm.controls['firstName'].touched && !registerForm.controls['firstName'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['firstName'].hasError('required')">
                            Please enter first name
                        </div>
                        <div *ngIf="registerForm.controls['firstName'].hasError('minlength')">
                            Please enter atleast 4 characters
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="lastName" id="lastName" placeholder=""
                        required aria-label="Enter lastname">
                    <label for="lastName" class="floating-label">Last Name</label>

                    <div *ngIf="registerForm.controls['lastName'].touched && !registerForm.controls['lastName'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['lastName'].hasError('required')">
                            Please enter last name
                        </div>
                        <div *ngIf="registerForm.controls['lastName'].hasError('minlength')">
                            Please enter atleast 4 characters
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="email" id="email" placeholder=""
                        pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required aria-label="Enter email">
                    <label for="email" class="floating-label">Email</label>

                    <div *ngIf="registerForm.controls['email'].touched && !registerForm.controls['email'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['email'].hasError('required')">
                            Please enter a email
                        </div>
                        <div *ngIf="registerForm.controls['email'].hasError('pattern')" aria-live="assertive">
                            Please enter email in correct format
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="password" id="password" placeholder=""
                        required minlength="6" pattern="^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$"
                        aria-label="Enter password">
                    <label for="password" class="floating-label">Password</label>
                    <div *ngIf="registerForm.controls['password'].touched && !registerForm.controls['password'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['password'].hasError('required')">
                            Please enter a password
                        </div>
                        <div *ngIf="registerForm.controls['password'].hasError('pattern')">
                            Password should contain a number, alphabet without space
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="confirmPassword" id="confirmPassword"
                        placeholder="" required minlength="6" aria-label="Enter confirmPassword">
                    <label for="confirmPassword" class="floating-label">Confirm Password</label>
                    <div *ngIf="registerForm.controls['confirmPassword'].touched && !registerForm.controls['confirmPassword'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['confirmPassword'].hasError('required')">
                            Please re-enter the password
                        </div>
                        <div *ngIf="registerForm.errors?.mismatch">
                            Password doesn't match
                        </div>
                    </div>
                    <div *ngIf="registerForm.controls['confirmPassword'].touched && registerForm.errors?.mismatch"
                        class="alert alert-danger">
                        Password doesn't match
                    </div>
                </div>

                <button type="submit" class="custom-btn common-btn" [disabled]="!registerForm.valid"
                    aria-label="Click Signup" aria-label="Signup">Signup</button>
            </form>
        </div>
    </section>
</div>

// src/pages/Register/index.jsx
import React, { Component } from "react";
import {
  checkValidEmail,
  checkValidPassword,
  checkNameValid,
} from "../../services/formServices";
import InputField from "../../components/InputField";
import "./Register.scss";

class Register extends Component {
  constructor(props) {
    super(props);
    this.state = {
      email: "",
      password: "",
      firstName: "",
      lastName: "",
      confirmPassword: "",

      errors: {
        email: "",
        password: [],
        firstName: "",
        lastName: "",
        confirmPassword: "",
      },
    };
  }

  // Handles input value changes for controlled component
  handleChange = (e) => {
    const { name, value } = e.target;
    if (!(name && value)) return;
    this.setState({
      [name]: value,
    });
  };

  // Handles form submission for controlled component
  handleSubmit = (e) => {
    e.preventDefault();
    const isEmailValid = checkValidEmail(this.state.email);
    const listOfpasswordErrors = checkValidPassword(this.state.password);
    const isFirstNameValid = checkNameValid(this.state.firstName);
    const isLastNameValid = checkNameValid(this.state.lastName);
    if (
      !isEmailValid ||
      !isFirstNameValid ||
      !isLastNameValid ||
      listOfpasswordErrors.length ||
      this.state.confirmPassword !== this.state.password
    ) {
      this.setErrors(
        isEmailValid,
        listOfpasswordErrors,
        isFirstNameValid,
        isLastNameValid
      );
      return;
    }
    this.submitForm();
    this.setState({
      email: "",
      password: "",
      firstName: "",
      lastName: "",
      confirmPassword: "",
    });
  };

  submitForm = () => {
    this.setState({
      errors: {
        email: "",
        password: [],
        firstName: "",
        lastName: "",
        confirmPassword: "",
      },
    });
  };

  setErrors = (
    isEmailValid,
    listOfpasswordErrors,
    isFirstNameValid,
    isLastNameValid
  ) => {
    const errors = {
      email: "",
      password: [],
      firstName: "",
      lastName: "",
      confirmPassword: "",
    };
    if (!isEmailValid) {
      errors.email = "Please enter a valid email ID";
    }
    if (listOfpasswordErrors.length) {
      errors.password = listOfpasswordErrors;
    }
    if (!isFirstNameValid)
      errors.firstName =
        "First name cannot be more than 15 characters or less than 2 characters";
    if (!isLastNameValid)
      errors.lastName =
        "Last name cannot be more than 15 characters or less than 2 characters";
    if (this.state.confirmPassword !== this.state.password)
      errors.confirmPassword = "Confirm password should match given password";
    this.setState({ errors });
  };

  render() {
    return (
      <section className="signup">
        <div className="signup-header">
          <span>
            <h1>Sign Up</h1>
            <p>We do not share your personal details with anyone</p>
          </span>
        </div>
        <div className="signup-form">
          <form onSubmit={this.handleSubmit}>
            {/* Name Fields */}
            <InputField
              fieldControl={"firstName"}
              fieldName="First Name"
              error={this.state.errors.firstName}
              value={this.state.firstName}
              handleChange={this.handleChange}
            />
            <InputField
              fieldControl={"lastName"}
              fieldName="Last Name"
              error={this.state.errors.lastName}
              value={this.state.lastName}
              handleChange={this.handleChange}
            />
            {/* Email Field */}
            <InputField
              fieldControl={"email"}
              error={this.state.errors.email}
              value={this.state.email}
              handleChange={this.handleChange}
            />
            {/* Password fields */}
            <InputField
              fieldControl={"password"}
              type={"password"}
              error={this.state.errors.password}
              value={this.state.password}
              handleChange={this.handleChange}
            />
            <InputField
              fieldControl={"confirmPassword"}
              fieldName="Confirm Password"
              type={"password"}
              error={this.state.errors.confirmPassword}
              value={this.state.confirmPassword}
              handleChange={this.handleChange}
            />
            <input
              aria-label="Sign up"
              type="submit"
              id="signup-button"
              value="Sign Up"
            />
          </form>
        </div>
      </section>
    );
  }
}

export default Register;
