// src/components/Header/Header.tsx
import React from "react";
import logo from "../../static/images/logo.png";
import cart from "../../static/images/cart.svg";
import "./Header.scss";

export const Header = () => {
    return (
        <header className="header">
            
            <div className="header__logo">
                <img src={logo} alt="Sabka Bazaar Logo"/>
            </div>

            <nav className="header__nav">

                <div className="nav--left">
                 <div>Home</div>
                 <div>Products</div>
                </div>

                <div className="nav--right">
                    <div>SignIn</div>
                    <div>Register</div>
                </div>

                <div className="nav--cart">
                    <div className="cart"><img src={cart} alt="cart"/></div>
                    <div>0 items</div>
                </div>

            </nav>
        </header>
    )
}

// frontend/sabkabazaar/src/app/shared/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.sass']
})
export class HeaderComponent implements OnInit {

  // productsLength$: Observable<number> = of(0);
  // @Output() openCart = new EventEmitter<void>();

  // constructor(readonly dataservice: DataService) {
  //   this.productsLength$ = this.dataservice.getselectedProdustsLength();
  // }

  ngOnInit(): void {
  }

  showCart() {
    // this.openCart.emit();
  }
}

<div class="header">
    <img class="logo" src="assets/images/logo.png">
    <nav>
        <ul>
            <li><a [routerLink]="['/home']" routerLinkActive="active">Home</a></li>
            <li><a [routerLink]="['/products']" routerLinkActive="active">Products</a></li>
        </ul>
    </nav>
    <div class="login">
        <ul>
            <li><a [routerLink]="['/login']" routerLinkActive="active">SignIn</a></li>
            <li><a [routerLink]="['/register']" routerLinkActive="active">Register</a></li>
        </ul>
        <button class="cart" (click)="showCart()">
            <img src="assets/images/cart.svg">
            <!-- {{productsLength$ | async}} Items -->
        </button>
    </div>
</div>
