// client/src/Pages/SignIn/sign-in.component.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useDispatch } from "react-redux";

import { userSignIn } from "../../reducer/user/user.actions";

import "./sign-in.styles.css";

const SignIn = () => {
  const [userCredentials, setUserCredentials] = useState({
    email: "",
    password: "",
  });

  const [errorMessage, setErrorMessage] = useState(null);

  const navigate = useNavigate();
  const dispatch = useDispatch();

  const handleChange = (event) => {
    const { name, value } = event.target;
    setUserCredentials({ ...userCredentials, [name]: value });
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    const { email, password } = userCredentials;
    setErrorMessage(null);
    if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(email)) {
      setErrorMessage("Invalid Email");
      return;
    }
    const savedUserCredentials = JSON.parse(
      localStorage.getItem("userCredentials")
    );
    if (
      savedUserCredentials &&
      (savedUserCredentials.email !== email ||
        savedUserCredentials.password !== password)
    ) {
      setErrorMessage("Invalid Credentials");
      return;
    }
    dispatch(userSignIn());
    navigate("/");
  };
  return (
    <div className='sign-in'>
      <div className='sign-in-title'>
        <h1>Login</h1>
        <p>Get access to your Orders, Whishlist and Recommendations</p>
      </div>
      <div className='signin-form'>
        <form onSubmit={handleSubmit}>
          <input
            type='email'
            name='email'
            id='email'
            value={userCredentials.email}
            onChange={handleChange}
            placeholder='Email'
            required
          />
          <input
            type='password'
            name='password'
            id='password'
            value={userCredentials.password}
            onChange={handleChange}
            placeholder='Password'
            required
          />
          {errorMessage && <div className='signup-error'>{errorMessage}</div>}
          <button type='submit' className='signin-button'>
            Login
          </button>
        </form>
      </div>
    </div>
  );
};
export default SignIn;

// Project/shopping-app/src/app/login/sign-in/sign-in.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.css']
})
export class SignInComponent implements OnInit {
  loginForm: FormGroup;
  loading = false;
  submitted = false;
  isValidUser = true;

  constructor( private router: Router ) {
    this.loginForm = new FormGroup({
    userEmail: new FormControl('', [Validators.required, Validators.pattern(/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/)]),
    password: new FormControl('', Validators.required),
  });
}

  ngOnInit(): void {}
  onSubmit(): void {
    this.submitted = true;
    if (this.loginForm.invalid) {
        return;
    } else if (this.loginForm.valid) {
      const itemsStr = localStorage.getItem('RegisteredUsers');
      const userDetails = itemsStr ? JSON.parse(itemsStr) : [];
      const loginDetails: any = JSON.stringify(this.loginForm.value);
      userDetails.map((user: any) => {
        const userData = JSON.parse(user);
        const loginData = JSON.parse(loginDetails);
        if ( userData.userEmail === loginData.userEmail &&  userData.password === loginData.password ) {
          this.isValidUser = true;
          sessionStorage.setItem('isUserLoggedIn', 'true');
          this.router.navigate(['./home']);
        }else {
          this.isValidUser = false;
        }
      });
    }
  }

  get f(): any { return this.loginForm.controls; }
}

<div class="login">
    <div class="row">
        <div class="col col-lg-6 col-md-4 col-sm-4 col-0 loginHeader">
            <h3>Login</h3>
            <p>Get access to your Orders, Wishlist and Recommendations</p>

        </div>
        <div class="col col-lg-6 col-md-8 col-sm-8 col-12 loginForm">
            <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
                <span class="error" *ngIf="!isValidUser">Invalid Credentails</span>
                <div class="form-group">
                    <input type="email" placeholder="Email" formControlName="userEmail"  [ngClass]="{ 'is-invalid': submitted && f.userEmail.errors }" />
                    <div *ngIf="submitted && f.userEmail.errors" class="error">
                        <div *ngIf="f.userEmail.errors.required" >Email is required</div>
                        <div *ngIf="f.userEmail.errors.pattern">Please provide valid email</div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="password" placeholder="Password" formControlName="password"  [ngClass]="{ 'is-invalid': submitted && f.password.errors }" />
                    <div *ngIf="submitted && f.password.errors" class="error">
                        <div *ngIf="f.password.errors.required">Password is required</div>
                    </div>
                </div>
                <div class="form-group">
                    <button  type="submit" >Login</button>
                </div>
            </form>
</div>
