// src/pages/Register.jsx
import React from "react";
import { Formik, Form } from "formik";
import { Link } from "react-router-dom";
import TextField from "../components/TextField";
import * as Yup from "yup";
import bcrypt from "bcryptjs";
import toast from "izitoast";

const RegisterForm = () => {
  const validate = Yup.object({
    firstName: Yup.string()
      .min(3, "First name must be 3 characters or more")
      .required("Required"),
    lastName: Yup.string()
      .min(3, "Last name must be 3 characters or more")
      .required("Required"),
    email: Yup.string()
      .email("Email is invalid")
      .required("Email is required")
      .test({
        name: "isPresent",
        message: "User with this email is already in system",
        test: (value) => {
          let users = JSON.parse(localStorage.getItem("users")) || [];
          return users.filter((user) => user.email.toLowerCase() === value)
            .length > 0
            ? false
            : true;
        },
      }),
    password: Yup.string()
      .min(8, "Password must be 8 characters or less")
      .required("Password is required"),
    confirmPassword: Yup.string()
      .oneOf([Yup.ref("password"), null], "Password must match")
      .required("Required"),
  });
  return (
    <Formik
      initialValues={{
        email: "",
        password: "",
        firstName: "",
        lastName: "",
        confirmPassword: "",
      }}
      validationSchema={validate}
      onSubmit={(value) => {
        let data = value;
        let password = data.password;

        // Creating hashed passwords
        let hashPassword = bcrypt.hashSync(password, 10);
        // updating password & confirmPassword with hash
        data["password"] = hashPassword;
        data["confirmPassword"] = hashPassword;
        // Deleting not required key
        delete data.confirmPassword;
        // Storing user data in local machince
        let users = JSON.parse(localStorage.getItem("users")) || [];
        localStorage.setItem(
          "users",
          JSON.stringify([...users].concat(data), null, 2)
        );
        // Showing Alert that user successfully registered to the app
        toast.success({ message: "Registered successfuly" });
        // Resetting form fields;
        const resetBtn = document.getElementById("resetBtn");
        resetBtn.click();
      }}
    >
      {(formik) => (
        <>
          <Form>
            <TextField
              name="firstName"
              type="text"
              label={"First Name"}
              id="firstName"
            />
            <TextField
              name="lastName"
              type="text"
              label={"Last Name"}
              id="lastName"
            />
            <TextField name="email" type="email" label="Email" id="email" />
            <TextField
              name="password"
              type="password"
              label="Password"
              id="password"
            />
            <TextField
              name="confirmPassword"
              type="password"
              label="Confirm Password"
              id="confirmPassword"
            />
            <button className="btn" type="submit" role={"button"}>
              Register
            </button>
            <button
              type="reset"
              hidden
              aria-hidden="true"
              role={"button"}
              id="resetBtn"
            >
              Reset
            </button>
          </Form>
          <h5 className="text-center mt-2">
            Already have an account?{" "}
            <Link to="/signin" className="px-2 py-1">
              Login
            </Link>
          </h5>
        </>
      )}
    </Formik>
  );
};

function Register(props) {
  return (
    <div
      className="py-5 px-md-5 px-3 login- d-flex justify-content-center align-items-center"
      role={"group"}
    >
      <div className="container max-auto">
        <div className="row">
          <div className="col-md-6">
            <h1 className="mb-3" aria-label="Login">
              Register
            </h1>
            <p aria-label="Login Description">
              We do not share your personal details with anyone
            </p>
          </div>
          <div className="col-md-6 mt-md-0 mt-5 ">
            <RegisterForm />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Register;

// src/app/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {
  registerForm: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group({
      firstName: ['', [Validators.required, Validators.minLength(4)]],
      lastName: ['', [Validators.required, Validators.minLength(4)]],
      email: ['', [Validators.required]],
      password: ['', [Validators.required]],
      confirmPassword: ['', [Validators.required]]
    }, { validator: this.matchPassword });
  }

  onRegister(): void {
    localStorage.setItem('registeredUser', JSON.stringify(this.registerForm.value));
    alert('User registered successfully. Please login');
    this.router.navigate(['auth/signin']);
  }

  matchPassword(control: AbstractControl): { [key: string]: boolean } | null {
    const password = control.get('password');
    const confirmPassword = control.get('confirmPassword');
    if (password.pristine || confirmPassword.pristine) {
      return null;
    }
    if (password && confirmPassword && password.value !== confirmPassword.value) {
      return { mismatch: true };
    } else {
      return null;
    }
  }

}

<div class="container my-5">
    <section class="row">
        <div class="col-lg-6">
            <p class="main-heading" aria-level="1" role="heading">Signup</p>
            <p>We do not share your personal details with anyone.</p>
        </div>

        <div class="col-lg-6">
            <form [formGroup]="registerForm" novalidate (ngSubmit)="onRegister()">
                <div class="form-group custom-group">
                    <input type="text" id="firstName" class="form-control" formControlName="firstName" placeholder=""
                        required aria-label="Enter firstName" autocomplete>
                    <label for="firstName" class="floating-label">First Name</label>

                    <div *ngIf="registerForm.controls['firstName'].touched && !registerForm.controls['firstName'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['firstName'].hasError('required')">
                            Please enter first name
                        </div>
                        <div *ngIf="registerForm.controls['firstName'].hasError('minlength')">
                            Please enter atleast 4 characters
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="lastName" id="lastName" placeholder=""
                        required aria-label="Enter lastname" autocomplete>
                    <label for="lastName" class="floating-label">Last Name</label>

                    <div *ngIf="registerForm.controls['lastName'].touched && !registerForm.controls['lastName'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['lastName'].hasError('required')">
                            Please enter last name
                        </div>
                        <div *ngIf="registerForm.controls['lastName'].hasError('minlength')">
                            Please enter atleast 4 characters
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="email" formControlName="email" id="email" placeholder=""
                        pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required aria-label="Enter email"
                        autocomplete>
                    <label for="email" class="floating-label">Email</label>

                    <div *ngIf="registerForm.controls['email'].touched && !registerForm.controls['email'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['email'].hasError('required')">
                            Please enter a email
                        </div>
                        <div *ngIf="registerForm.controls['email'].hasError('pattern')" aria-live="assertive">
                            Please enter email in correct format
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="password" formControlName="password" id="password" placeholder=""
                        required minlength="6" pattern="^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$"
                        aria-label="Enter password" autocomplete="off">
                    <label for="password" class="floating-label">Password</label>
                    <div *ngIf="registerForm.controls['password'].touched && !registerForm.controls['password'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['password'].hasError('required')">
                            Please enter a password
                        </div>
                        <div *ngIf="registerForm.controls['password'].hasError('pattern')">
                            Password should contain a number and an alphabet without space
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="password" formControlName="confirmPassword" id="confirmPassword"
                        placeholder="" required minlength="6" aria-label="Enter confirmPassword" autocomplete="off">
                    <label for="confirmPassword" class="floating-label">Confirm Password</label>
                    <div *ngIf="registerForm.controls['confirmPassword'].touched && !registerForm.controls['confirmPassword'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['confirmPassword'].hasError('required')">
                            Please re-enter the password
                        </div>
                    </div>
                    <div *ngIf="registerForm.errors?.mismatch" class="alert alert-danger">
                        Password doesn't match
                    </div>
                </div>

                <button type="submit" class="custom-btn common-btn" [disabled]="!registerForm.valid"
                    aria-label="Click Signup" aria-label="Signup">Signup</button>
            </form>
        </div>
    </section>
</div>
