// src/components/ProductCard/ProductCard.tsx
import React from "react";
import type { Product } from "../../types/customTypes";
import "./ProductCard.scss";

export const ProductCard = (product: Product) => {
  return (
    <div className="product-card">

      <div className="product-card__title">{product.name}</div>
      
      <div className="product-card__image">
        <img src={product.imageURL} alt={product.name}/>
      </div>
      <div className="product-card__description">{product.description}</div>

      <div className="product-card__price-button">
        <div>MRP. Rs {product.price}</div>
        <button>Buy Now</button>
      </div>

    </div>
  )
}

// frontend/sabkabazaar/src/app/shared/product-card/product-card.component.ts
import { Component,Input, Output, OnInit, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.sass']
})
export class ProductCardComponent implements OnInit {
  
  @Input() product: any;
  @Output() addProductInCart = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
  }

  addProduct(product: any){
    this.addProductInCart.emit(product)
  }
}

<div class="product">
    <h2>{{product.name}}</h2>
    <div class="product-details">
        <figure>
            <img [src]="product.imageURL" [alt]="product.name">
        </figure>
        <div class="description">
            <p>{{product.description}}</p>
            <button (click)="addProduct(product)" class="at-price">Buy Now @ Rs{{product.price}}</button>
        </div>
        <div class="price">
            <span class="price-detail">MRP Rs. {{product.price}}</span>
            <button (click)="addProduct(product)" class="buy">
            Buy Now <span class="at-price">@ Rs{{product.price}}</span>
          </button>
        </div>
    </div>
</div>
