// client/src/pages/Products/ProductCard/index.tsx
import React from "react";
import styles from "./product.module.scss";

export const ProductCard: React.FC<{
  product: Product;
  onButtonClick?: (e: any) => void;
  disable?: boolean;
}> = ({ product, onButtonClick, disable }) => {
  return (
    <div className={styles.product_card} tabIndex={0}>
      <h3>{product.name}</h3>
      <img src={product.imageURL} alt={product.name} />
      <p className={styles.description}>{product.description}</p>
      <div className={styles.card_footer}>
        <p>MRP Rs.{product.price}</p>
        <button onClick={onButtonClick} disabled={disable}>
          Buy Now
        </button>
      </div>
    </div>
  );
};

// ClientSide/src/app/product-card/product-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Products } from '../models/Products';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.scss'],
})
export class ProductCardComponent implements OnInit {
  @Input() product: Products;
  constructor() {}

  ngOnInit(): void {}
}

<div class="product-card-cont">
  <h2 class="product-card-title">{{product.name}}</h2>
  <img class="product-card-img" [src]="product.imageURL" [alt]="product.description" width="100%">
  <div class="product-card-subtext">
    <p>{{product.description}}</p>
  </div>
  <div class="product-buy">
    <span class="product-card-cost">MRP Rs{{product.price}}</span>
    <button class="btn">Buy Now</button>
  </div>
</div>
