// src/components/ProductCard/ProductCard.tsx
import React from "react";
import type { Product } from "../../types/customTypes";
import "./ProductCard.scss";

export const ProductCard = (product: Product) => {
  return (
    <div className="product-card">

      <div className="product-card__title">{product.name}</div>
      
      <div className="product-card__image">
        <img src={product.imageURL} alt={product.name}/>
      </div>
      <div className="product-card__description">{product.description}</div>

      <div className="product-card__price-button">
        <div>MRP. Rs {product.price}</div>
        <button>Buy Now</button>
      </div>

    </div>
  )
}

// ClientSide/src/app/product-card/product-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Products } from '../models/Products';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.scss'],
})
export class ProductCardComponent implements OnInit {
  @Input() product: Products;
  constructor() {}

  ngOnInit(): void {}
}

<div class="product-card-cont">
  <h2 class="product-card-title">{{product.name}}</h2>
  <img class="product-card-img" [src]="product.imageURL" [alt]="product.description" width="100%">
  <div class="product-card-subtext">
    <p>{{product.description}}</p>
  </div>
  <div class="product-buy">
    <span class="product-card-cost">MRP Rs{{product.price}}</span>
    <button class="btn">Buy Now</button>
  </div>
</div>
