// src/app/login-signup/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { LoginSignUpService } from '../login-signup.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignUpComponent implements OnInit {

  validationMessages: { [key: string]: { [key: string]: string } };

  registrationForm: FormGroup;

  constructor(
    private _router: Router,
    private _headerService: LoginSignUpService,
    private _fb: FormBuilder
  ) {
    this.validationMessages = {
      firstName: {
        required: this._headerService.REQUIRED_ERROR,
        pattern: this._headerService.NAME_PATTERN_ERROR,
        minlength: this._headerService.NAME_LENGTH_ERROR,
      },
      lastName: {
        required: this._headerService.REQUIRED_ERROR,
        pattern: this._headerService.NAME_PATTERN_ERROR,
        minlength: this._headerService.NAME_LENGTH_ERROR,
      },
      email: {
        required: this._headerService.REQUIRED_ERROR,
        minLength: this._headerService.EMAIL_MINLENGTH_ERROR,
        pattern: this._headerService.EMAIL_PATTERN,
      },
      password: {
        required: this._headerService.REQUIRED_ERROR,
        minLength: this._headerService.PASSWORD_LENGTH_ERROR,
        pattern: this._headerService.PASSWORD_PATTERN,
      },
      confirmPassword: {
        required: this._headerService.REQUIRED_ERROR,
        minLength: this._headerService.PASSWORD_LENGTH_ERROR,
        compare: this._headerService.PASSWORD_COMPARE_ERROR,
      },
    };
  }

  ngOnInit(): void {
    this.registrationForm = this._fb.group({
      firstName: [
        '',
        [
          Validators.required,
          Validators.pattern(this._headerService.NAME_REGEX),
        ],
      ],
      lastName: [
        '',
        [
          Validators.required,
          Validators.pattern(this._headerService.NAME_REGEX),
        ],
      ],
      email: [
        '',
        [
          Validators.required,
          Validators.minLength(8),
          Validators.pattern(this._headerService.EMAIL_REGEX),
        ],
      ],
      password: [
        '',
        [
          Validators.required,
          Validators.minLength(8),
          Validators.pattern(this._headerService.PASSWORD_REGEX),
        ],
      ],
      confirmPassword: [
        '',
        [
          Validators.required,
          Validators.minLength(8),
          Validators.pattern(this._headerService.PASSWORD_REGEX),
        ],
      ],
    },
    {validator: this.passwordConfirming});
  }

  submitRegistrationForm(): void {
    if (this.registrationForm.valid) {
      localStorage.setItem(this.registrationForm.get('email').value, this.registrationForm.get('password').value);
      this._router.navigate(['SabkaBaZaar/login']);
      console.log(localStorage);
      
    } else {
      this._headerService.validateAllFormFields(this.registrationForm);
    }
  }

  passwordConfirming(c: AbstractControl): { compare: boolean } {
    if (c.get('password').value !== c.get('confirmPassword').value) {
        return {compare: true};
    }
  }

}

<div class="container">
    <div class="row register-row">
        <div class="col-lg-6 col-sm-12  LoginRegText">
            <h1 class="title">Signup</h1>
            <p class="title-description">We do not share your personal details with anyone.
            <p>
        </div>
        <div class="col-lg-6 col-sm-12">
            <form [formGroup]="registrationForm" (submit)="submitRegistrationForm()">
                <div class="form-group">
                    <label for="firstName" class="bmd-label-floating">First Name</label>
                    <input type="text" class="form-control" id="firstName" formControlName="firstName" />
                </div>
                <div *ngIf="
              (registrationForm.get('firstName').touched ||
                registrationForm.get('firstName').dirty) &&
              registrationForm.get('firstName').invalid
            " class="error-msg">
                    {{
                    registrationForm.get("firstName")?.errors.required
                    ? validationMessages.firstName.required
                    : validationMessages.firstName.pattern
                    }}
                </div>
                <div class="form-group">
                    <label for="lastName" class="bmd-label-floating">Last Name</label>
                    <input type="text" class="form-control" id="lastName" formControlName="lastName" />
                </div>
                <div *ngIf="
            (registrationForm.get('lastName').touched ||
              registrationForm.get('lastName').dirty) &&
            registrationForm.get('lastName').invalid
          " class="error-msg">
                    {{
                    registrationForm.get("lastName")?.errors.required
                    ? validationMessages.lastName.required
                    : validationMessages.lastName.pattern
                    }}
                </div>
                <div class="form-group">
                    <label for="email" class="bmd-label-floating">Email</label>
                    <input type="email" class="form-control" id="email" formControlName="email" />
                </div>
                <div *ngIf="
            (registrationForm.get('email').touched ||
              registrationForm.get('email').dirty) &&
            registrationForm.get('email').invalid
          " class="error-msg">
                    {{
                    registrationForm.get("email")?.errors.required
                    ? validationMessages.email.required
                    : validationMessages.email.pattern
                    }}
                </div>
                <div class="form-group">
                    <label for="password" class="bmd-label-floating">Password</label>
                    <input type="password" class="form-control" id="password" formControlName="password" />
                </div>
                <div *ngIf="
            (registrationForm.get('password').touched ||
              registrationForm.get('password').dirty) &&
            registrationForm.get('password').invalid
          " class="error-msg">
                    {{
                    registrationForm.get("password")?.errors.required
                    ? validationMessages.password.required
                    : validationMessages.password.pattern
                    }}
                </div>
                <div class="form-group">
                    <label for="confirmPassword" class="bmd-label-floating">Confirm Password</label>
                    <input type="password" class="form-control" id="confirmPassword"
                        formControlName="confirmPassword" />
                </div>
                <div *ngIf="
            (registrationForm.get('confirmPassword').touched ||
              registrationForm.get('confirmPassword').dirty) &&
            registrationForm.get('confirmPassword').invalid
          " class="error-msg">
                    {{
                    registrationForm.get("confirmPassword")?.errors.required
                    ? validationMessages.confirmPassword.required
                    : validationMessages.confirmPassword.compare
                    }}
                </div>

                <button type="submit" class="btn btn-danger btn-raised action-btn">Signup</button>
            </form>
        </div>
    </div>
</div>

// app/src/authComponent/signUp.jsx
import React, {  useEffect, useState } from 'react';
import { Col, Form,  Row } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import './form.scss';

const SignUp = () => {
    const initialValue = { firstname: "", lastname: "", email: "", password: "", confirmpassword: "" };
    const [formValues, setFormValues] = useState(initialValue);
    const [errors, setErrors] = useState(false);
    const [isSubmit, setIsSubmit] = useState(false)
    const navigate = useNavigate();
    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormValues({ ...formValues, [name]: value });

    }
    const handleSubmit = (e) => {
        e.preventDefault();
        setErrors(validate(formValues));
        setIsSubmit(true);
    }
    const validate = (values) => {
        const formerrors = {};
        const regx = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;
        if (!values.firstname) {
            formerrors.firstname = 'Firstname is required';
        }
        if (!values.lastname) {
            formerrors.lastname = 'Lastname is required';
        }
        if (!values.email) {
            formerrors.email = 'Email is required';
        } else if (!regx.test(values.email)) {
            formerrors.email = 'This is not valid email format';
        }
        if (!values.password) {
            formerrors.password = 'Password is required';
        }
        if (!values.confirmpassword) {
            formerrors.confirmpassword = 'Confirm password is required';
        } else if (values.password !== values.confirmpassword) {
            formerrors.confirmpassword = 'Password entered did not match!'
        }
        return formerrors;
    }

    useEffect(() => {
        console.log(errors)
        if (Object.keys(errors).length === 0 && isSubmit) {
            navigate('/')
        }
    }, [errors])

    return (
        <div className='form-sec'>
            <Row className="justify-content-md-center">
                <Col md={6}>
                    <div className='signup-data'>
                        <h3>SignUp</h3>
                        <p>We do not share your personal details with anyone</p>
                    </div>
                </Col>
                <Col md={4}>
                    <Form onSubmit={handleSubmit} >
                        <div className='form-group'>
                            
                            <input type="text" placeholder='First Name' className={errors.firstname ? 'error-border' : ''} name="firstname" value={formValues.firstname} onChange={handleChange} />
                            <p className='error'>{errors.firstname}</p>
                        </div>
                        <div className='form-group'>
                          
                            <input type="text" placeholder='Last Name' className={errors.lastname ? 'error-border' : ''} name="lastname" value={formValues.lastname} onChange={handleChange} />
                            <p className='error'>{errors.lastname}</p>
                        </div>
                        <div className='form-group'>
                           
                            <input type="text" placeholder='Email' className={errors.email ? 'error-border' : ''} name="email" value={formValues.email} onChange={handleChange} />
                            <p className='error'>{errors.email}</p>
                        </div>
                        <div className='form-group'>
                          
                            <input type="password" placeholder='Password' className={errors.password ? 'error-border' : ''} name="password" value={formValues.password} onChange={handleChange} />
                            <p className='error'>{errors.password}</p>
                        </div>
                        <div className='form-group'>
                            
                            <input type="text" placeholder='Confirm password' className={errors.confirmpassword ? 'error-border' : ''} name="confirmpassword" value={formValues.confirmpassword} onChange={handleChange} />
                            <p className='error'>{errors.confirmpassword}</p>
                        </div>
                        <button type="submit" className='btn-cls login-btn'>Signup</button>
                    </Form>
                </Col>
            </Row>
        </div>
    );
}

export default SignUp;
