// src/app/pages/home/category/category.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Observable, of} from 'rxjs';

import {CategoryModel} from '../../../models/home/category.model';

@Component({
  selector: 'app-category',
  templateUrl: './category.component.html',
  styleUrls: ['./category.component.scss']
})
export class CategoryComponent implements OnInit {

  @Input() categoryDetails: CategoryModel = {} as CategoryModel;
  @Input() isLeftAlign = false;

  constructor() {
  }

  ngOnInit(): void {
  }

}

<section class="row align-items-center py-4"
         [ngClass]="{'flex-row-reverse': isLeftAlign}"
         *ngIf="categoryDetails">
    <div class="col-4 col-md-4">
        <img [src]="categoryDetails.imageUrl" [alt]="categoryDetails.name" class="img-fluid">
    </div>
    <div class="col-8 col-md-8 d-flex flex-column align-items-center details-wrapper">
        <h3 class="text-center">{{ categoryDetails.name }}</h3>
        <p class="text-center">{{ categoryDetails.description }}</p>
        <app-button [content]="'Explore ' + categoryDetails.key"></app-button>
    </div>
</section>

// src/components/categories/Category.jsx
import React from "react";
import { Link } from "react-router-dom";
import placeholderImg from "../../static/images/default.jpeg";

const Category = ({ data, align }) => {
  return (
    <>
      <section className={`category ${align}`}>
        <div className="container-fluid mx-auto">
          <div className="row">
            <div className="col-4 col-sm-6 p-0">
              <img
                src={data.imageUrl || placeholderImg}
                alt={data.name}
                className="category-image"
              />
            </div>
            <div className="col-8 col-sm-6 d-flex justify-content-center align-items-center p-0">
              <div className="category-description text-center d-flex flex-column justify-content-center align-items-center">
                <h3 role={"heading"} className="mb-3">
                  {data.name}
                </h3>
                <p role={"definition"} className="mb-3 fs-small">
                  {data.description}
                </p>
                <Link to={`/category/${data.id}`} className="link-btn">
                  Explore {data.key}
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Category;
