// client/src/components/login/Login.jsx
import React, { useState } from "react";
import { Button, Form } from "react-bootstrap";
import { useNavigate } from "react-router-dom";
import "./login.css";
const loginFieldInputs = {
  email: "",
  password: "",
};
const Login = () => {
  const navigate = useNavigate();
  const [fieldValue, setFieldValue] = useState(loginFieldInputs);
  const { email, password } = fieldValue;
  const handleLoginChanges = (event) => {
    const { name, value } = event.target;
    setFieldValue({ ...fieldValue, [name]: value });
  };

  const handleLogin = async (event) => {
    event.preventDefault();
    navigate("/home");
  };
  return (
    <div className="auth-container">
      <div className="login-container">
        <h1>Login</h1>
        <p>Get access to your Orders, Wishlist and Recommendations</p>
      </div>
      <div className="login-container">
        <Form onSubmit={handleLogin}>
          <div className="group">
            <label className="form-input-label">Email</label>
            <input
              type="email"
              className="form-input"
              required
              name="email"
              value={email}
              onChange={handleLoginChanges}
            />
          </div>
          <div className="group">
            <label className="form-input-label">Password</label>
            <input
              type="password"
              className="form-input"
              required
              name="password"
              value={password}
              onChange={handleLoginChanges}
              minLength="6"
              pattern="^[a-zA-Z0-9]*$"
            />
          </div>
          <Button className="customSubmit mt-3" size="sm" type="submit">
            Login
          </Button>
        </Form>
      </div>
    </div>
  );
};

export default Login;

// bazaar/src/app/Component/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {


    loginForm : FormGroup
  constructor(private fb : FormBuilder, private _route :  Router) { }

  ngOnInit(): void {
    this.loginForm = this.fb.group({
      
      email: ['', [Validators.required, Validators.email]],
        password : ['', [Validators.minLength(6), Validators.required]]
    });
  }

  get email() {
    return this.loginForm.get('email');
  }
  get password() {
    return this.loginForm.get('password');
  }

  onSubmit(){
    //console.log(this.loginForm.value);
    this._route.navigate(['/home'])
    
  }

}

<section>
    <div class="row">
        <div class="span-1-of-2">
            <h3>
                Login
            </h3>
            <p>
                Get access to your Order, Wishlist and Recommendations
            </p>
        </div>
        <div class="span-1-of-2">
            <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" novalidate>
                <div class="user-input-wrp">
                    <input type="email" class="inputText" formControlName="email" required />
                    <span class="floating-label">Email</span>
                    <div *ngIf="!email?.valid && (email?.dirty ||email?.touched)">
                        <div class="error-class"  [hidden]="!email.errors.required">
                            Email is required
                        </div>
                        <div class="error-class"  [hidden]="!email.errors.email">
                            Incorrect email
                        </div>

                    </div>
                </div>
                <div class="user-input-wrp">
                    <input type="password" class="inputText" required formControlName="password" />
                    <span class="floating-label">Password</span>
                    <div *ngIf="!password?.valid && (password?.dirty ||password?.touched)">
                        <div class="error-class"  [hidden]="!password.errors.required">
                            password is required
                        </div>
                        <div class="error-class"  [hidden]="!password.errors.minlength">
                            Min Length is 6
                        </div>
                    </div>
                </div>
                <div>
                    <button type="submit" class="btn submit-btn" [disabled]="!loginForm.valid">Submit</button>
                </div>

            </form>

        </div>

    </div>
</section>
