// src/components/CategoryBanner.jsx
import React from "react";
import "./CategoryBanner.css";
function CategoryBanner(props) {
  const { category } = props;

  return (
    <div className="banner-component">
      <div className="image-container">
        <img
          src={category.imageUrl}
          alt={category.name}
          className="banner-image"
        />
      </div>
      <div className="content">
        <h2 className="heading"> {category.name} </h2>
        <p className="desc"> {category.description} </p>
        <a href="/" role="link" className="link-button">
          {" "}
          Explore {category.key}{" "}
        </a>
      </div>
    </div>
  );
}

export default CategoryBanner;

// shopping-cart-client/src/app/home-page/category-banner/category-banner.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { NavigationExtras, Router } from '@angular/router';
import { Categories } from 'src/app/models/Categories';

@Component({
  selector: 'app-category-banner',
  templateUrl: './category-banner.component.html',
  styleUrls: ['./category-banner.component.css'],
})
export class CategoryBannerComponent implements OnInit {
  @Input() categoriesData: Categories[];

  constructor(private router: Router) {}

  ngOnInit(): void {}

  OnExploreClick(id: string) {
    const navigationExtras: NavigationExtras = {
      state: { id },
    };
    this.router.navigate(['/plp'], navigationExtras);
  }
}

<div
  class="categories-container"
  [style.flex-direction]="isOdd ? 'row-reverse' : 'row'"
  *ngFor="
    let category of categoriesData;
    let i = index;
    let isOdd = odd;
    let isEven = even
  "
>
  <div class="category-image">
    <img
      src="assets{{ category.imageUrl }}"
      [alt]="category.name"
      srcset="
        {{category.imageUrl_small}}   320w,
        {{category.imageUrl_medium}}  640w,
        assets{{category.imageUrl}}  1024w
      "
      sizes="(min-width: 1024px) 40vw,
           (min-width: 768px) 50vw,
           50vw"
    />
  </div>
  <article class="category-desc">
    <h3>{{ category?.name }}</h3>
    <p>{{ category?.description }}</p>

    <a
      href="javascript: void(0)"
      class="btn explore-link"
      (click)="OnExploreClick(category.id)"
      >Explore {{ category?.key }}</a
    >
  </article>
</div>
