// src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {
  registerForm: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group({
      firstName: ['', [Validators.required, Validators.minLength(4)]],
      lastName: ['', [Validators.required, Validators.minLength(4)]],
      email: ['', [Validators.required]],
      password: ['', [Validators.required]],
      confirmPassword: ['', [Validators.required]]
    }, { validator: this.matchPassword });
  }

  onSubmit() {
    this.router.navigate(['/home']);
  }

  matchPassword(abs: AbstractControl): { mismatch: boolean } {
    if (abs.get('password').value !== abs.get('confirmPassword').value) {
      return { mismatch: true };
    }
  }

}

<div class="container my-5">
    <section class="row">
        <div class="col-lg-6">
            <h2>Signup</h2>
            <p>We do not share your personal details with anyone.</p>
        </div>

        <div class="col-lg-6">
            <form [formGroup]="registerForm" novalidate (ngSubmit)="onSubmit()">
                <div class="form-group custom-group">
                    <input type="text" id="firstName" class="form-control" formControlName="firstName" placeholder=""
                        required aria-label="Enter firstName">
                    <label for="firstName" class="floating-label">First Name</label>

                    <div *ngIf="registerForm.controls['firstName'].touched && !registerForm.controls['firstName'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['firstName'].hasError('required')">
                            Please enter first name
                        </div>
                        <div *ngIf="registerForm.controls['firstName'].hasError('minlength')">
                            Please enter atleast 4 characters
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="lastName" id="lastName" placeholder=""
                        required aria-label="Enter lastname">
                    <label for="lastName" class="floating-label">Last Name</label>

                    <div *ngIf="registerForm.controls['lastName'].touched && !registerForm.controls['lastName'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['lastName'].hasError('required')">
                            Please enter last name
                        </div>
                        <div *ngIf="registerForm.controls['lastName'].hasError('minlength')">
                            Please enter atleast 4 characters
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="email" id="email" placeholder=""
                        pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required aria-label="Enter email">
                    <label for="email" class="floating-label">Email</label>

                    <div *ngIf="registerForm.controls['email'].touched && !registerForm.controls['email'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['email'].hasError('required')">
                            Please enter a email
                        </div>
                        <div *ngIf="registerForm.controls['email'].hasError('pattern')" aria-live="assertive">
                            Please enter email in correct format
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="password" id="password" placeholder=""
                        required minlength="6" pattern="^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$"
                        aria-label="Enter password">
                    <label for="password" class="floating-label">Password</label>
                    <div *ngIf="registerForm.controls['password'].touched && !registerForm.controls['password'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['password'].hasError('required')">
                            Please enter a password
                        </div>
                        <div *ngIf="registerForm.controls['password'].hasError('pattern')">
                            Password should contain a number, alphabet without space
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="confirmPassword" id="confirmPassword"
                        placeholder="" required minlength="6" aria-label="Enter confirmPassword">
                    <label for="confirmPassword" class="floating-label">Confirm Password</label>
                    <div *ngIf="registerForm.controls['confirmPassword'].touched && !registerForm.controls['confirmPassword'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['confirmPassword'].hasError('required')">
                            Please re-enter the password
                        </div>
                        <div *ngIf="registerForm.errors?.mismatch">
                            Password doesn't match
                        </div>
                    </div>
                    <div *ngIf="registerForm.controls['confirmPassword'].touched && registerForm.errors?.mismatch"
                        class="alert alert-danger">
                        Password doesn't match
                    </div>
                </div>

                <button type="submit" class="custom-btn common-btn" [disabled]="!registerForm.valid"
                    aria-label="Click Signup" aria-label="Signup">Signup</button>
            </form>
        </div>
    </section>
</div>

// shopping-website/src/pages/Register.jsx
import { Formik } from "formik";
import React from "react";
import Input from "../components/form/Input";
import "./Register.scss";
import * as Yup from "yup";

const Register = () => {

    const passwordRegex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;

  const validations = Yup.object({
    firstName: Yup.string().required("First Name is Required"),
    lastName: Yup.string().required("Last Name is Required"),
    email: Yup.string()
      .required("Email is Required")
      .email("Invalid email address"),
    password: Yup.string()
      .required("password is required")
      .matches(
        passwordRegex,
        "password must contain one number,one letter,without spaces and minimum 6 characters long"
      ),
    confirmPassword: Yup.string().oneOf(
      [Yup.ref("password"), null],
      "Passwords must match"
    ),
  });

  return (
    <section className="registerContainer">
      <div className="registerDesc">
        <h1 style={{ fontWeight: "bold" }}>Signup</h1>
        <p className="registerHeading">
          We do not share your personal details with anyone
        </p>
      </div>
      <div className="registerForm">
        <Formik
          initialValues={{
            firstName: "",
            lastName: "",
            email: "",
            password: "",
            confirmPassword: "",
          }}
          validationSchema = {validations}
          onSubmit={(values) => {
              console.log('here');
            console.log(values);
          }}
        >
          {({
            values,
            touched,
            errors,
            handleChange,
            handleBlur,
            handleSubmit,
            isSubmitting,
          }) => (
            <form onSubmit={handleSubmit}>
              <Input
                type="text"
                name="firstName"
                label="First Name"
                placeholder="First Name"
                value={values.firstName}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.firstName && touched.firstName && errors.firstName}
              />
              <Input
                type="text"
                name="lastName"
                label="Last Name"
                placeholder="Last Name"
                value={values.lastName}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.lastName && touched.lastName && errors.lastName}
              />
              <Input
                type="email"
                name="email"
                label="Email"
                placeholder="Email"
                value={values.email}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.email && touched.email && errors.email}
              />
              <Input
                type="password"
                name="password"
                label="Password"
                placeholder="Password"
                value={values.password}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.password && touched.password && errors.password}
              />
              <Input
                type="password"
                name="confirmPassword"
                label="Confirm Password"
                placeholder="Confirm Password"
                value={values.confirmPassword}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.confirmPassword && touched.confirmPassword && errors.confirmPassword}
              />
              <button type="submit" className="submitButton">
          <p
            style={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "center",
            }}
          >
            Register
          </p>
        </button>
            </form>
          )}
        </Formik>
      </div>
    </section>
  );
};

export default Register;
