// src/app/pages/register/register.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {Router} from '@angular/router';

import {CustomValidator} from '../../services/validators/match-password';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {

  registerForm: FormGroup;

  constructor(private formBuilder: FormBuilder,
              private router: Router) {
  }

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group({
      firstname: [null, [Validators.required]],
      lastname: [null, [Validators.required]],
      email: [null, [Validators.required, Validators.email]],
      password: [
        null,
        [
          Validators.required,
          Validators.minLength(6),
          CustomValidator.patternValidator(/^[a-zA-Z0-9 ]*$/, {hasNumberAndAlphabet: true}),
          CustomValidator.patternValidator(/^\S*$/, {hasNoSpace: true})
        ]
      ],
      confirmPassword: [null, Validators.required]
    }, {
      validator: CustomValidator.match('password', 'confirmPassword')
    })
  }

  onRegister() {
    this.router.navigate(['home'])
  }

}

<div class="container">
  <div class="row mt-3">
    <div class="col-12 col-md-5 offset-md-1">
      <h2 class="mb-2 mt-4">Signup</h2>
      <p>We do not share your personal details with anyone.</p>
    </div>
    <form class="col-12 col-md-4 mb-4" [formGroup]="registerForm" (ngSubmit)="onRegister()">
      <div class="input-box mt-5">
        <input name="firstname" type="text" formControlName="firstname" id="firstname" />
        <label class="floating-label" for="firstname">First Name</label>
      </div>

      <ng-container *ngIf="!registerForm.get('firstname').valid && registerForm.get('firstname').touched">
        <span *ngIf="registerForm.get('firstname').errors['required']" class="error">Firstname is required</span>
      </ng-container>

      <div class="input-box mt-5">
        <input name="lastname" type="text" formControlName="lastname" id="lastname" />
        <label class="floating-label" for="lastname">Last Name</label>
      </div>

      <ng-container *ngIf="!registerForm.get('lastname').valid && registerForm.get('lastname').touched">
        <span *ngIf="registerForm.get('lastname').errors['required']" class="error">Lastname is required</span>
      </ng-container>

      <div class="input-box mt-5">
        <input name="email" type="email" formControlName="email" id="email" />
        <label class="floating-label" for="email">Email</label>
      </div>

      <ng-container *ngIf="!registerForm.get('email').valid && registerForm.get('email').touched">
        <span *ngIf="registerForm.get('email').errors['required']" class="error">Email is required</span>
        <span *ngIf="registerForm.get('email').errors['email']" class="error">Email is invalid</span>
      </ng-container>

      <div class="input-box mt-5">
        <input name="password" type="password" formControlName="password" id="password" />
        <label class="floating-label" for="password">Password</label>
      </div>

      <ng-container *ngIf="!registerForm.get('password').valid && registerForm.get('password').touched">
        <span *ngIf="registerForm.get('password').errors['required']" class="error">Password is required</span>
        <span *ngIf="registerForm.get('password').errors['hasNumberAndAlphabet']" class="error">Must have number and alphabets</span>
        <span *ngIf="registerForm.get('password').errors['hasNoSpace']" class="error">Spaces are not allowed</span>
        <span *ngIf="registerForm.get('password').errors['minlength']" class="error">Minimum length is 6</span>
      </ng-container>

      <div class="input-box mt-5">
        <input name="confirmPassword" type="password" formControlName="confirmPassword" id="confirmPassword" />
        <label class="floating-label" for="confirmPassword">Confirm Password</label>
      </div>

      <ng-container *ngIf="!registerForm.get('confirmPassword').valid && registerForm.get('confirmPassword').touched">
        <span *ngIf="registerForm.get('confirmPassword').errors['required']" class="error">Password is required</span>
        <span *ngIf="registerForm.get('confirmPassword').errors['match']" class="error">Password not match</span>
      </ng-container>

      <div class="mt-4"></div>
      <app-button content="Signup" [isFullWidth]="true" type="submit"
                  [disabled]="registerForm.status === 'INVALID'"></app-button>
    </form>
  </div>
</div>

// shopping-website/src/pages/Register.jsx
import { Formik } from "formik";
import React from "react";
import Input from "../components/form/Input";
import "./Register.scss";
import * as Yup from "yup";

const Register = () => {

    const passwordRegex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;

  const validations = Yup.object({
    firstName: Yup.string().required("First Name is Required"),
    lastName: Yup.string().required("Last Name is Required"),
    email: Yup.string()
      .required("Email is Required")
      .email("Invalid email address"),
    password: Yup.string()
      .required("password is required")
      .matches(
        passwordRegex,
        "password must contain one number,one letter,without spaces and minimum 6 characters long"
      ),
    confirmPassword: Yup.string().oneOf(
      [Yup.ref("password"), null],
      "Passwords must match"
    ),
  });

  return (
    <section className="registerContainer">
      <div className="registerDesc">
        <h1 style={{ fontWeight: "bold" }}>Signup</h1>
        <p className="registerHeading">
          We do not share your personal details with anyone
        </p>
      </div>
      <div className="registerForm">
        <Formik
          initialValues={{
            firstName: "",
            lastName: "",
            email: "",
            password: "",
            confirmPassword: "",
          }}
          validationSchema = {validations}
          onSubmit={(values) => {
              console.log('here');
            console.log(values);
          }}
        >
          {({
            values,
            touched,
            errors,
            handleChange,
            handleBlur,
            handleSubmit,
            isSubmitting,
          }) => (
            <form onSubmit={handleSubmit}>
              <Input
                type="text"
                name="firstName"
                label="First Name"
                placeholder="First Name"
                value={values.firstName}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.firstName && touched.firstName && errors.firstName}
              />
              <Input
                type="text"
                name="lastName"
                label="Last Name"
                placeholder="Last Name"
                value={values.lastName}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.lastName && touched.lastName && errors.lastName}
              />
              <Input
                type="email"
                name="email"
                label="Email"
                placeholder="Email"
                value={values.email}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.email && touched.email && errors.email}
              />
              <Input
                type="password"
                name="password"
                label="Password"
                placeholder="Password"
                value={values.password}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.password && touched.password && errors.password}
              />
              <Input
                type="password"
                name="confirmPassword"
                label="Confirm Password"
                placeholder="Confirm Password"
                value={values.confirmPassword}
                onChange={handleChange}
                onBlur={handleBlur}
                onError={errors.confirmPassword && touched.confirmPassword && errors.confirmPassword}
              />
              <button type="submit" className="submitButton">
          <p
            style={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "center",
            }}
          >
            Register
          </p>
        </button>
            </form>
          )}
        </Formik>
      </div>
    </section>
  );
};

export default Register;
