// client/src/app/products/components/product-card/product-card.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Product } from 'src/app/shared/models/product';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.scss'],
})
export class ProductCardComponent implements OnInit {
  @Input('product') product: Product = new Product();

  @Output('addToCart') addToCart = new EventEmitter<Product>();
  @Output('removeFromCart') removeFromCart = new EventEmitter<Product>();

  constructor() {}

  ngOnInit(): void {}
}

<div class="card m-0">
  <h5 class="card-title font-weight-bold px-2 pt-2" id="name-{{ product.id }}">
    {{ product.name }}
  </h5>

  <div class="d-flex d-lg-block align-content-center">
    <div class="image-container t-half-width">
      <picture>
        <source [srcset]="product.imageURL + '.webp'" type="image/webp" />
        <source
          [srcset]="product.imageURL + '.' + product.imageType"
          [type]="'image/' + product.imageType"
        />
        <img
          alt=""
          class="card-img-top align-self-center"
          [src]="product.imageURL + '.' + product.imageType"
        />
      </picture>
    </div>

    <div class="card-body t-half-width">
      <div class="product-description-container h-100">
        <p
          class="card-text product-description p-1"
          [title]="product.description"
        >
          {{ product.description }}
        </p>
      </div>
    </div>
  </div>

  <div class="card-body pt-0">
    <div
      class="d-flex justify-content-end justify-content-lg-between align-items-center"
    >
      <p class="card-text d-lg-block d-none m-0">MRP Rs {{ product.price }}</p>

      <span class="sr-only" aria-live="assertive">
        {{ product.quantityInCart }} items of {{ product.name }} in cart
      </span>

      <button
        class="btn btn-primary"
        *ngIf="!product.quantityInCart; else productInCart"
        [attr.aria-describedby]="'name-' + product.id"
        (click)="addToCart.emit(product)"
      >
        <span>Buy Now</span>
        <span class="d-block d-lg-none"> @ Rs {{ product.price }}</span>
      </button>

      <ng-template #productInCart>
        <div class="d-flex">
          <button
            class="btn btn-primary"
            aria-label="Remove item from cart"
            [attr.aria-describedby]="'name-' + product.id"
            (click)="removeFromCart.emit(product)"
          >
            -
          </button>
          <span class="quantity-in-cart mx-2">
            {{ product.quantityInCart }}
          </span>
          <button
            class="btn btn-primary"
            aria-label="Add item to cart"
            [attr.aria-describedby]="'name-' + product.id"
            (click)="addToCart.emit(product)"
          >
            +
          </button>
        </div>
      </ng-template>
    </div>
  </div>
</div>

// src/components/cards/ProductCard.tsx
import React from "react";
import { Button, Card, Col, Row } from "antd";
import EllipsisText from "react-ellipsis-text";
export default function ProductCard(props) {
  const { data, addToCart } = props;
  return (
    <Card
      hoverable
      title={
        <span className="bold fontsize16 p5">
          <EllipsisText text={data.name} length={50} />
        </span>
      }
      className="product-card"
    >
      <Row className="flex flexible">
        <Col span={24} className="card-img w50">
          <img alt="example" src={data.imageURL} />
        </Col>
        <Col span={24} className="card-description medium p5 w50">
          <EllipsisText text={data.description} length={100} />
        </Col>
      </Row>
      <Col
        span={24}
        className="absolute flex justify-content-space-between w100 p10 align-items-center"
      >
        <div className="medium">MRP Rs.{data.price}</div>
        <div>
          <Button
            className="w100 white card-action-btn medium"
            type="text"
            onClick={() => addToCart(data)}
          >
            Buy Now
          </Button>
        </div>
      </Col>
    </Card>
  );
}
