// src/components/pages/Home.jsx
import React from "react";
import axios from "axios";
import SliderComponent from "./../SliderComponent";
import CategoryBanner from "./../CategoryBanner";
import "../Home.scss";

function Home() {
  const [banner, setBanner] = React.useState([]);
  const [categories, setCategories] = React.useState([]);
  React.useEffect(() => {
    axios.get("http://localhost:5000/banners").then(
      (res) => {
        setBanner(res.data);
      },
      (err) => {
        console.error(err);
      }
    );
    axios.get("http://localhost:5000/categories").then(
      (res) => {
        setCategories(res.data);
      },
      (err) => {
        console.error(err);
      }
    );
  }, []);
  return (
    <div className="body-section">
      <SliderComponent banner={banner} />
      {categories.map(
        (item) =>
          item.enabled && <CategoryBanner category={item} key={item.key} />
      )}
    </div>
  );
}

export default Home;

// client/src/views/Home.vue
<template>
  <div class="home">
    <Categories
      v-if="categories.length > 0"
      :banners="banners"
      :categories="categories"
    />
  </div>
</template>

<script>
// @ is an alias to /src
import Categories from "../components/Categories.vue";
import axios from "axios";
export default {
  name: "Home",
  components: {
    Categories,
  },
  data() {
    return {
      banners: [],
      categories: [],
    };
  },
  created() {
    axios.get("http://localhost:5000/banners").then((res) => {
      this.banners = res.data;
    });

    axios.get("http://localhost:5000/categories").then((res) => {
      this.categories = res.data.filter((val) => val.imageUrl);
    });
  },
};
</script>

<style scoped>
.home {
  margin-top: 2rem;
}
</style>
