// client/src/Components/cart/cart.component.jsx
import React from "react";
import { useSelector, useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";

import { addItem, removeItem } from "../../reducer/cart/cart.actions";

import "./cart.styles.css";

const Cart = () => {
  const cartItems = useSelector((state) => state.cart.cartItems);
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const totalPrice = cartItems.reduce(
    (acc, item) => acc + item.quantity * item.price,
    0
  );
  return (
    <div className='cart-page'>
      {cartItems.length === 0 ? (
        <div className='empty-cart'>
          <div className='empty-cart-title'>No items in your cart</div>
          <div className='empty-cart-desc'>
            Your favourite items are just a click away
          </div>
          <button
            className='btn-cart btn-bottom'
            onClick={() => navigate("/products")}
          >
            Start Shopping
          </button>
        </div>
      ) : (
        <div className='cart-items-container'>
          <div className='cart-title'>
            <p>My Cart ({cartItems.length} items)</p>
          </div>
          <div className='cart-items-list'>
            {cartItems.map((item) => (
              <div key={item.id} className='cart-item-container'>
                <div className='cart-item'>
                  <img src={item.imageURL} alt={item.name} />
                  <div className='item-desc'>
                    <div>{item.name}</div>
                    <div className='button-container'>
                      <button
                        onClick={() => dispatch(removeItem(item))}
                        className='btn-inc-dec'
                      >
                        -
                      </button>
                      <div className='item-counter'>{item.quantity}</div>
                      <button
                        onClick={() => dispatch(addItem(item))}
                        className='btn-inc-dec'
                      >
                        +
                      </button>
                      <div className='item-price'>X&nbsp; Rs.{item.price}</div>
                    </div>
                  </div>
                  <div className='item-total'>
                    Rs.{item.price * item.quantity}
                  </div>
                </div>
              </div>
            ))}
            <div className='cheap-slogan'>
              <img src='/static/images/lowest-price.png' alt='lowest-price' />
              <p>You won't find it cheaper anywhere</p>
            </div>
          </div>
          <div className='cart-footer'>
            <p>Promo code can be applied on payment page</p>
            <button onClick={() => navigate("/")} className='btn-cart'>
              <div className='btn-container'>
                <div className='checkout-title'>Proceed to Checkout</div>
                <div className='cart-total-price'>Rs.{totalPrice} &gt;</div>
              </div>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Cart;

// bazaar/src/app/modules/cart/component/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from 'src/app/modules/shared/Interface/product';
import { ShareService } from 'src/app/modules/shared/service/share.service';


@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss']
})
export class CartComponent implements OnInit {

   cartItem  :Product[] = []
   totalItem : number = 0;
   totalPrice : number = 0;

  constructor( private _shareService : ShareService) { }

  ngOnInit(): void {
    this.cartItem = JSON.parse(localStorage.getItem('cartItem'));
    if(this.cartItem) {
    this.calculateTotal();
    }
    this._shareService.getCartValue().subscribe((res:Product[]) => {
      this.cartItem = res;
     this.calculateTotal();
    })
    this._shareService.updateFooterStatus(false);

  }

  calculateTotal(){
    this.totalItem = this.cartItem.reduce(function (prev, cur) {
      return prev  + cur.quantity;
    }, 0);

    this.totalPrice = this.cartItem.reduce(function(prev , cur){
      return prev + cur.quantity * cur.price
    }, 0)
  }

  addItem(item){
    this._shareService.addCart(item);
  }

  removeItem(item){
    this._shareService.removeCart(item);
  }

  ngOnDestroy(){
    this._shareService.updateFooterStatus(true);
  }

}

<div class="container">
    <section class="cart__container" *ngIf=" cartItem != null && cartItem.length> 0; else empty">
        <div>
            <h1>My Cart <span> ( {{totalItem}} item) </span></h1>
            <ul>
                <li *ngFor="let item of cartItem">
                    <div class="row">
                        <div class="span-1-of-3">
                            <img [src]="item?.imageURL" alt="{{item?.name}}">
                        </div>
                        <div class="span-2-of-3">
                            <h2 [aria-labelledby]="item?.name">{{item?.name}}</h2>
                            <div class="cart__details">
                                <button type="button" class="btn" (click)="removeItem(item)">-</button>
                                <span class="cart__quantity">{{item?.quantity}}</span>
                                <button type="button" class="btn" (click)="addItem(item)">+</button>
                                <span>
                                    * {{item?.price}}
                                </span>
                            </div>
                        </div>
                        <div class="span-1-of-3">
                            RS {{item?.quantity * item?.price}}
                        </div>
                    </div>
                </li>
            </ul>
            <aside class="cart__tag-line">
                <img src="../../../assets/images/lowest-price.png"
                    alt="Banner displaying, You wont find it cheaper anywhere" />
                <p>You wont find it cheaper anywhere</p>
            </aside>
        </div>
        <div class="cart__footer">
            <p>Promo code can be apply on payment page</p>
            <button class="btn checkout-btn" type="button" routerLink="/home">Proceed to Checkout
                <span>
                    {{totalPrice}} >
                </span>
            </button>

        </div>
    </section>

    <ng-template #empty>
        <section>
            <div class="cart__empty">
                <h3>No Items in your cart</h3>
                <p> Your favourite items are just a click away</p>
            </div>
            <button class="btn" type="button" routerLink="/home">Start Shopping</button>
        </section>
    </ng-template>
</div>
