// src/component/cart/Cart.jsx
import React, { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { addRemoveToCart } from "../../redux/cart/actionCreator";
import "./cart.scss";

function Cart(props) {
  const cartData = useSelector((state) => state.getCartDetail.cartItems);
  const dispatch = useDispatch();

  const manageCartItems = (productData, type) => {
    let prodObj = {
      id: productData.id,
      type: type,
    };
    dispatch(addRemoveToCart(prodObj));
  };
  return (
    <div className="app-cart">
      <div className="cart-block">
        <div className="cart-head">
          <p>My Cart ({cartData.length}item)</p>
          <button onClick={() => props.status(false)}>X</button>
        </div>
        <ul className="cart-mid">
          {cartData &&
            cartData.map((product, index) => (
              <li className="product-block" key={product.id} tabIndex="0">
                <img
                  src={product.image}
                  alt={product.name}
                  loading="lazy"
                  width="45"
                ></img>
                <div className="prod-detail">
                  <p>{product.name}</p>
                  <div className="quantity">
                    <button
                      className="cart-btn"
                      onClick={manageCartItems.bind(null, product, "decrement")}
                    >
                      <span>-</span>
                    </button>
                    <span>{product.count}</span>
                    <button
                      className="cart-btn"
                      onClick={manageCartItems.bind(null, product, "increment")}
                    >
                      <span>+</span>
                    </button>
                    <span>x</span>
                    <span>{product.price}</span>
                  </div>
                </div>
                <p>
                  <b>{product.price * product.count}</b>
                </p>
              </li>
            ))}

          {cartData.length ? (
            <li className="block2" tabIndex="0">
              <img
                src="/static/images/lowest-price.webp"
                alt="lowest Price Logo"
                loading="lazy"
                width="100"
              ></img>
              <p>You Wont find cheeper anywhere</p>
            </li>
          ) : (
            <li className="centre">
              <p>
                <b>No Items in your cart</b>
              </p>
              <p>Your favourite items are just a click away</p>
            </li>
          )}
        </ul>
        <div className="cart-foot centre">
          {cartData.length ? (
            <>
              <p>Promo Code can be applied to payment page</p>
              <button className="app-btn">
                <span>Proceed to Checkout</span>
                <span>
                  Rs :
                  {Object.values(cartData).reduce(
                    (t, { price, count }) => t + price * count,
                    0
                  )}
                </span>
              </button>
            </>
          ) : (
            <button className="app-btn centre">Start Shopping</button>
          )}
        </div>
      </div>
    </div>
  );
}

export default React.memo(Cart);

// src/app/cart/cart.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss']
})
export class CartComponent implements OnInit {
  @Output() cartClosed= new EventEmitter();
  constructor() { }

  ngOnInit() {
  }

  closeCart(){
    this.cartClosed.emit();
  }

}


<section class="cart-container" id="js-cart">
    <div class="visuallyhidden" id="closeButtonId">Close Cart</div>
    <!-- Header -->
    <header class="main-header">
        <h1 class="disp-inline">My Cart&nbsp;<span class="cart-count">(0 items)</span></h1>
        <p tabindex="0" role="button" class="pull-right cursor-pointer" (click)="closeCart()" aria-labelledby="closeButtonId">&#10006;</p>
    </header>


    <!-- Main content -->
    <main>
            <!-- cart's Cards -->
            <div class="card-panel clearfix margin-top-10" *ngFor="let cart of cartList; let i = index">
                <figure class="pull-left">
                    <img src="{{cart.imageURL}}" alt="Product image">
                </figure>
                <section class="cart-values pull-left margin-left-20">
                    <header class="margin-bottom-15">
                        <h6 class="ellipse cart-title" title="{{cart.name}}">{{cart.name}}</h6>
                    </header>
                    <button  aria-label="decrement" class="minus disp-inline text-center" (click)="modifyItems(cart,'decrement',i)">
                        <span class="sign">&#8722;</span>
                    </button>
                    <span class="value margin-left-20 margin-right-20">{{cart.count}}</span>
                    <button  aria-label="increment" class="plus margin-right-20 disp-inline text-center" (click)="modifyItems(cart,'increment',i)">
                        <span class="sign">&#43;</span>
                    </button>
                    
                    <div class="visuallyhidden" id="item-count-price">{{cart.count}} items at {{cart.price}} each</div>
                    <div  role="text" class="price disp-inline" aria-labelledby="item-count-price">X&nbsp;&nbsp;&nbsp;&nbsp;Rs.{{cart.price}}</div>
                </section>
                <div class="total-price">
                    <p class="visuallyhidden" id="total-product-price">{{cart.count * cart.price}} Rupees</p>
                    <div role="text" aria-labelledby="total-product-price"><data value="{{cart.count * cart.price}}" >Rs.{{cart.count * cart.price}}</data></div>
                </div>
            </div>
            <!-- Offer section -->
            <div class="offer margin-top-10 clearfix" *ngIf="cartList?.length">
                <figure class="pull-left"><img src="../../assets/images/lowest-price.png" alt="Lowest Price logo"></figure>
                <p class="disp-inline margin-left-20">You won't find it cheaper anywhere.</p>
            </div>


            <!-- No item in the card -->
            <section *ngIf="!cartList?.length" class="no-item-exception text-center">
                <h5>No items in your cart</h5>
                <p class="font-13">Your favourite items are just a click away</p>
            </section>
    </main>


    <!-- Footer -->
    <footer class="cart-footer margin-top-5 padding-10">
        <p *ngIf="cartList?.length" class="font-14 text-center margin-bottom-10">Promo code can be applied on payment page</p>
        <button *ngIf="cartList?.length" (click)="closeCart()" class="cart-btn clearfix padding-10" role="button" aria-label="Proceed checkout button">
            <p class="pull-left margin-left-5 font-14">Proceed Checkout</p>
            <p class="pull-right margin-right-5 font-14">Rs.{{totalPrice}}&nbsp;&gt;</p>
        </button>
        <button *ngIf="!cartList?.length" (click)="exploreShopping()" class="cart-btn clearfix padding-10" role="button" aria-label="Start Shopping">
            <p class="margin-left-5 font-14" >Start Shopping</p>
        </button>
    </footer>
</section>
