// src/components/Category/category-banner.component.jsx
import React from "react";
import "./category-banner.styles.scss";
import { Link } from 'react-router-dom';

function CategoryBanner(props) {
  const { category } = props;

  return (
    <div className="banner-component">
      <div className="image-container">
        <img
          src={category.imageUrl}
          alt={category.name}
          className="banner-image"
        />
      </div>
      <div className="content">
        <h2 className="heading"> {category.name} </h2>
        <p className="desc"> {category.description} </p>
        <span className="link-button">
        <Link to='/products'>{" "}
          Explore {category.key}{" "}</Link>
        </span>
      </div>
    </div>
  );
}

export default CategoryBanner;

// ClientSide/src/app/home-page/category-banner/category-banner.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Categories } from 'src/app/models/Categories';

@Component({
  selector: 'app-category-banner',
  templateUrl: './category-banner.component.html',
  styleUrls: ['./category-banner.component.scss']
})
export class CategoryBannerComponent implements OnInit {
  @Input() categoriesData: Categories[];

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="categories-container" [style.flex-direction]="isOdd ? 'row-reverse' : 'row'" *ngFor="
      let category of categoriesData;
      let i = index;
      let isOdd = odd;
      let isEven = even
    ">
  <div class="category-image">
    <img [src]="category.imageUrl" [alt]="category.name" srcset="
          {{category.imageUrl_small}}   320w,
          {{category.imageUrl_medium}}  640w,
          {{category.imageUrl}}        1024w
        " sizes="(min-width: 60rem) 80vw,
           (min-width: 40rem) 90vw,
           100vw" />
  </div>
  <article class="category-desc">
    <h3>{{ category.name }}</h3>
    <p>{{ category.description }}</p>

    <button class="btn">Explore {{ category.key }}</button>
  </article>
</div>
