// client/src/components/login/Login.jsx
import React, { useState } from "react";
import { Col, Container, Button, Form } from "react-bootstrap";
import "./login.css";

const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <div className="auth-container">
      <div className="login-container">
        <h1>Login</h1>
        <p>Get access to your Orders, Wishlist and Recommendations</p>
      </div>
      <div className="login-container">
        <Form>
          <div className="group">
            <label className="form-input-label">Email</label>
            <input type="email" className="form-input" required name="email" />
          </div>
          <div className="group">
            <label className="form-input-label">Password</label>
            <input
              type="password"
              className="form-input"
              required
              name="password"
            />
          </div>
          <Button id="customSubmit" className="mt-3" size="sm" type="submit">
            Login
          </Button>
        </Form>
      </div>
    </div>
  );
};

export default Login;

// src/app/pages/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';
import {Router} from '@angular/router';

import {CustomValidator} from '../../services/validators/match-password';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  loginForm: FormGroup;

  constructor(private formBuilder: FormBuilder,
              private router: Router) {
  }

  ngOnInit(): void {
    this.loginForm = this.formBuilder.group({
      email: [null, [Validators.required, Validators.email]],
      password: [
        null,
        [
          Validators.required,
          Validators.minLength(6),
          CustomValidator.patternValidator(/^[A-Za-z0-9 _]*[A-Za-z0-9][A-Za-z0-9 _]*$/, {hasNumberAndAlphabet: true}),
          CustomValidator.patternValidator(/^\S*$/, {hasNoSpace: true})
        ]
      ]
    })
  }

  onLogin() {
    this.router.navigate(['home']);
  }

}

<div class="container">
  <div class="row align-items-center mt-3">
    <div class="col-12 col-md-5 offset-md-1">
      <h2 class="mb-2">Login</h2>
      <p>Get Access to your orders, Wishlist and recommendations</p>
    </div>
    <form class="col-12 col-md-4 mb-4" [formGroup]="loginForm" (ngSubmit)="onLogin()">
      <div class="input-box">
        <input name="email" label="Email" type="text" formControlName="email" id="email" />
        <label class="floating-label" for="email">Email</label>
      </div>

      <ng-container *ngIf="!loginForm.get('email').valid && loginForm.get('email').touched">
        <span *ngIf="loginForm.get('email').errors['required']" class="error">Email is required</span>
        <span *ngIf="loginForm.get('email').errors['email']" class="error">Email is invalid</span>
      </ng-container>

      <div class="input-box mt-5">
        <input name="password" label="Password" type="password" formControlName="password" id="password" />
        <label class="floating-label" for="password">Password</label>
      </div>

      <ng-container *ngIf="!loginForm.get('password').valid && loginForm.get('password').touched">
        <span *ngIf="loginForm.get('password').errors['required']" class="error">Password is required</span>
      </ng-container>

      <div class="mt-4"></div>

      <app-button content="Login" type="submit" [isFullWidth]="true"></app-button>
    </form>
  </div>
</div>
