// bazaar/src/app/Component/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { ShareServiceService } from 'src/app/service/share-service.service';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss']
})
export class CartComponent implements OnInit {

   cartItem  = [];
   totalItem : number = 0;
   totalPrice : number = 0;

  constructor( private _shareService : ShareServiceService) { }

  ngOnInit(): void {
    this.cartItem = JSON.parse(atob(localStorage.getItem('cartItem')));
    this.calculateTotal();
    this._shareService.getCartValue().subscribe((res:any) => {
      this.cartItem = res;
     this.calculateTotal();
    })

    this._shareService.updateFooterStatus(false);

  }

  calculateTotal(){
    this.totalItem = this.cartItem.reduce(function (prev, cur) {
      return prev  + cur.quantity;
    }, 0);

    this.totalPrice = this.cartItem.reduce(function(prev , cur){
      return prev + cur.quantity * cur.price
    }, 0)
  }



  addItem(item){
    this._shareService.addCart(item);
  }

  removeItem(item){
    this._shareService.removeCart(item);
  }

  ngOnDestroy(){
    this._shareService.updateFooterStatus(true);
  }

}


<div class="container">
<section class="cart-container" *ngIf=" cartItem != null && cartItem.length> 0; else empty">
    <div class="wrap-text">
    <h1>My Cart <span> ( {{totalItem}} item) </span></h1>
    <ul>
        <li  *ngFor="let data of cartItem">
            <div class="row">
                <div class="span-1-of-3">
                <img [src]="data?.imageURL" alt="{{data?.name}}">
            </div>
            <div class="span-2-of-3">
                    <h4>{{data?.name}}</h4>
                    <a href="javascript:void(0)" class="btn" (click)="removeItem(data)">-</a>
                    <span class="quantity-class">{{data?.quantity}}</span>
                    <a href="javascript:void(0)" class="btn" (click)="addItem(data)">+</a>
                    <span>
                        * {{data?.price}}
                    </span>
            </div>
            <div class="span-1-of-3">
                RS {{data?.quantity * data?.price}}
            </div></div>
        </li>
    </ul>
    <aside class="tag-line">
        <img
          src="../../../assets/images/lowest-price.png"
          alt="Banner displaying, You wont find it cheaper anywhere"
        />
        <p>You wont find it cheaper anywhere</p>
      </aside>
    </div>
    <div class="cart-footer">
    <p>Promo code can be apply on payment page</p>
    <button class="btn checkout-btn" type="button " routerLink="/home">Proceed to Checkout
        <span>
            {{totalPrice}} >
        </span>
    </button>
    
</div>
</section>

<ng-template #empty>
    <section>
    <div class="empty-cart">
       <h3>No Items in your cart</h3> 
       <p> Your favourite items are just a click away</p> 
    
      
    </div>
    <button class="btn" type="button" routerLink="/home">Start Shopping</button>
    </section> 
    </ng-template>
</div>

// client/src/Components/cart/cart.component.jsx
import React from "react";
import { useSelector, useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";

import { addItem, removeItem } from "../../reducer/cart/cart.actions";

import "./cart.styles.css";

const Cart = () => {
  const cartItems = useSelector((state) => state.cart.cartItems);
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const totalPrice = cartItems.reduce(
    (acc, item) => acc + item.quantity * item.price,
    0
  );
  return (
    <div className='cart-page'>
      {cartItems.length === 0 ? (
        <div className='empty-cart'>
          <div className='empty-cart-title'>No items in your cart</div>
          <div className='empty-cart-desc'>
            Your favourite items are just a click away
          </div>
          <button
            className='btn-cart btn-bottom'
            onClick={() => navigate("/products")}
          >
            Start Shopping
          </button>
        </div>
      ) : (
        <div className='cart-items-container'>
          <div className='cart-title'>
            <p>My Cart ({cartItems.length} items)</p>
          </div>
          <div className='cart-items-list'>
            {cartItems.map((item) => (
              <div key={item.id} className='cart-item-container'>
                <div className='cart-item'>
                  <img src={item.imageURL} alt={item.name} />
                  <div className='item-desc'>
                    <div>{item.name}</div>
                    <div className='button-container'>
                      <button
                        onClick={() => dispatch(removeItem(item))}
                        className='btn-inc-dec'
                      >
                        -
                      </button>
                      <div className='item-counter'>{item.quantity}</div>
                      <button
                        onClick={() => dispatch(addItem(item))}
                        className='btn-inc-dec'
                      >
                        +
                      </button>
                      <div className='item-price'>X&nbsp; Rs.{item.price}</div>
                    </div>
                  </div>
                  <div className='item-total'>
                    Rs.{item.price * item.quantity}
                  </div>
                </div>
              </div>
            ))}
            <div className='cheap-slogan'>
              <img src='/static/images/lowest-price.png' alt='lowest-price' />
              <p>You won't find it cheaper anywhere</p>
            </div>
          </div>
          <div className='cart-footer'>
            <p>Promo code can be applied on payment page</p>
            <button onClick={() => navigate("/")} className='btn-cart'>
              <div className='btn-container'>
                <div className='checkout-title'>Proceed to Checkout</div>
                <div className='cart-total-price'>Rs.{totalPrice} &gt;</div>
              </div>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Cart;
