// src/app/features/cart/cart/cart.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from 'src/app/store/app.reducer';
import { ICartItem } from '../../../shared/models/cart-item.model';
import { addProduct, deleteProduct } from '../store/actions/cart.actions';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.sass'],
})
export class CartComponent implements OnInit {
  @Output() close = new EventEmitter();
  cartItem!: ICartItem[];
  constructor(private store: Store<AppState>) {}

  ngOnInit(): void {
    this.store.select('cartList').subscribe((cartList) => {
      this.cartItem = cartList.cart;
    });
  }

  closeCart() {
    this.close.emit('');
  }

  plusQuantity(item: ICartItem) {
    this.store.dispatch(addProduct(item));
  }

  minusQuantity(item: ICartItem) {
    this.store.dispatch(deleteProduct({ id: item.product.id }));
  }

  get totalAmount(): number {
    let total = 0;
    for (let item of this.cartItem) {
      total += item.product.price * item.quantity;
    }
    return total;
  }
}

<div class="container">
  <div class="header">
    <h3>My Cart({{ cartItem.length }} Item)</h3>
    <span aria-colspan="close-button" (click)="closeCart()" class="close"
      >X</span
    >
  </div>
  <div *ngIf="!cartItem.length; else cartContentItem" class="content">
    <div class="no-items">
      <div>
        <h3>No items in cart</h3>
        <p>Your favourite items are just a click away</p>
      </div>
    </div>
  </div>
  <ng-template #cartContentItem>
    <div class="content">
      <div *ngFor="let item of cartItem" class="cart-item">
        <div class="left-section">
          <img
            [src]="'../../assets/' + item.product.imageURL"
            [alt]="item.product.name"
          />
        </div>
        <div class="right-section">
          <h4>{{ item.product.name }}</h4>
          <div class="detail">
            <div class="quantity">
              <span (click)="minusQuantity(item)" class="minus circle">-</span>
              <span class="count">{{ item.quantity }}</span>
              <span (click)="plusQuantity(item)" class="circle">+</span>
              <span class="multiplier"> x </span>
              <span class="per-piece-price">Rs.{{ item.product.price }}</span>
            </div>
            <h3 class="total">Rs.{{ item.product.price * item.quantity }}</h3>
          </div>
        </div>
      </div>
      <div class="lowest-price">
        <img
          src="../../assets/static/images/lowest-price.png"
          alt="lowest prive tag"
        />
        <div class="lowest-price-txt">You won't find it cheaper anywhere</div>
      </div>
    </div>
  </ng-template>
  <div *ngIf="cartItem.length; else startShopping" class="footer">
    <div class="promo-code">Promo code can be appplied on payment page</div>
    <a href="#" class="checkout">
      <span> Proceed to Checkout</span>
      <span> Rs.{{ totalAmount }}</span>
    </a>
  </div>
  <ng-template #startShopping>
    <div class="footer">
      <a href="#" class="start-shopping">
        <span> Start Shopping</span>
      </a>
    </div>
  </ng-template>
</div>

// client/src/Components/cart/cart.component.jsx
import React from "react";
import { useSelector, useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";

import { addItem, removeItem } from "../../reducer/cart/cart.actions";

import "./cart.styles.css";

const Cart = () => {
  const cartItems = useSelector((state) => state.cart.cartItems);
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const totalPrice = cartItems.reduce(
    (acc, item) => acc + item.quantity * item.price,
    0
  );
  return (
    <div className='cart-page'>
      {cartItems.length === 0 ? (
        <div className='empty-cart'>
          <div className='empty-cart-title'>No items in your cart</div>
          <div className='empty-cart-desc'>
            Your favourite items are just a click away
          </div>
          <button
            className='btn-cart btn-bottom'
            onClick={() => navigate("/products")}
          >
            Start Shopping
          </button>
        </div>
      ) : (
        <div className='cart-items-container'>
          <div className='cart-title'>
            <p>My Cart ({cartItems.length} items)</p>
          </div>
          <div className='cart-items-list'>
            {cartItems.map((item) => (
              <div key={item.id} className='cart-item-container'>
                <div className='cart-item'>
                  <img src={item.imageURL} alt={item.name} />
                  <div className='item-desc'>
                    <div>{item.name}</div>
                    <div className='button-container'>
                      <button
                        onClick={() => dispatch(removeItem(item))}
                        className='btn-inc-dec'
                      >
                        -
                      </button>
                      <div className='item-counter'>{item.quantity}</div>
                      <button
                        onClick={() => dispatch(addItem(item))}
                        className='btn-inc-dec'
                      >
                        +
                      </button>
                      <div className='item-price'>X&nbsp; Rs.{item.price}</div>
                    </div>
                  </div>
                  <div className='item-total'>
                    Rs.{item.price * item.quantity}
                  </div>
                </div>
              </div>
            ))}
            <div className='cheap-slogan'>
              <img src='/static/images/lowest-price.png' alt='lowest-price' />
              <p>You won't find it cheaper anywhere</p>
            </div>
          </div>
          <div className='cart-footer'>
            <p>Promo code can be applied on payment page</p>
            <button onClick={() => navigate("/")} className='btn-cart'>
              <div className='btn-container'>
                <div className='checkout-title'>Proceed to Checkout</div>
                <div className='cart-total-price'>Rs.{totalPrice} &gt;</div>
              </div>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Cart;
