// src/components/signUp/signUp.component.jsx
import React, { useState } from "react";
import CustomButton from "../custom-button/custom-button.component";
import FormInput from "../FormInput/FormInput.component";
import "./signUp.styles.scss";
import { withRouter } from "react-router-dom";


const SignUp = ({history}) => {
  const [userCredentials, setCredentials] = useState({
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    confirmPassword: "",
  });
  const [inputError, setInputError] = useState({
    email: "",
    password: "",
    confirmPassword: "",
  });

  const { firstName, lastName, email, password, confirmPassword } =
    userCredentials;

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (password !== confirmPassword) {
      return;
    }
    history.push(`/`);
  };

  const handleChange = (event) => {
    const { value, name } = event.target;
    setCredentials({ ...userCredentials, [name]: value });
    if (event.target.name === "email") {
      const emailPattern = /^[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[A-Za-z]+$/;

      if (!emailPattern.test(event.target.value)) {
        const emailError = "Please add valid email pattern wich includes @";
        setInputError({ ...inputError, [name]: emailError });
      } else {
        setInputError({ ...inputError, [name]: "" });
      }
    }

    if (event.target.name === "password") {
      const passworPattern = /(?=^.{6,10}$)(?=.*\d)(?=.*[a-zA-Z])(?!.*\s)/;

      if (!passworPattern.test(event.target.value)) {
        const passwordError =
          "Please add valid Password (min-length 6, atleast 1 alpha numeric and no space)";
        setInputError({ ...inputError, [name]: passwordError });
      } else {
        setInputError({ ...inputError, [name]: "" });
      }
    }

    if (event.target.name === "confirmPassword") {
      if (password !== event.target.value) {
        setInputError({ ...inputError, [name]: "Password do not match" });
      } else {
        setInputError({ ...inputError, [name]: "" });
      }
    }
  };

  return (
    <div className="sign-up">
      <div className="signUp__content">
        <h2 className="title">Signup</h2>
        <span>We do not share your personal details with anyone.</span>
      </div>
      <form onSubmit={handleSubmit} className="signUp__form">
        <FormInput
          name="firstName"
          type="text"
          label="First Name"
          value={firstName}
          handleChange={handleChange}
          required
        />
        <FormInput
          name="lastName"
          type="text"
          label="Last Name"
          value={lastName}
          handleChange={handleChange}
          required
        />
        <FormInput
          name="email"
          type="email"
          label="Email"
          value={email}
          handleChange={handleChange}
          required
          error={inputError.email}
        />
        <FormInput
          name="password"
          type="password"
          label="Password"
          value={password}
          handleChange={handleChange}
          required
          error={inputError.password}
        />
        <FormInput
          name="confirmPassword"
          type="password"
          label="Confirm Password"
          value={confirmPassword}
          handleChange={handleChange}
          required
          error={inputError.confirmPassword}
        />
        <CustomButton
          type="submit"
          className="buttons"
          disabled={
            inputError.email ||
            inputError.password ||
            inputError.confirmPassword
          }
        >
          Signup
        </CustomButton>
      </form>
    </div>
  );
};
export default withRouter(SignUp);

// frontend/src/app/auth/components/signup/signup.component.ts
import { Component, ElementRef, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignupComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  onSubmit(signupFormInfo: any) {
    console.log(signupFormInfo.value);
  }

}

<section class="custom-flex-container">
    <article>
        <h2>Signup</h2>
        <p>We do not share your personal details with anyone.</p>
    </article>
    <form class="bazar-signup-form" #signupForm="ngForm" (ngSubmit)="onSubmit(signupForm)">
        <div class="custom-form-group">
            <label for="firstName">First Name</label>
            <input type="text" id="firstName" name="firstName" class="custom-input" required #fname="ngModel" ngModel />
            <div class="custom-error" *ngIf="fname.touched && fname.valid">shsjh</div>
        </div>
        <div class="custom-form-group">
            <label for="lastName">Last Name</label>
            <input type="text" id="lastName" name="lastName" class="custom-input" required #lname="ngModel" ngModel />
        </div>
        <div class="custom-form-group">
            <label for="email">Email</label>
            <input type="email" id="email" name="email" class="custom-input" required #email="ngModel" ngModel />
        </div>
        <div class="custom-form-group">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" class="custom-input" minlength="6" #password="ngModel"
                required ngModel />
        </div>
        <div class="custom-form-group">
            <label for="confirmPassword">Confirm Password</label>
            <input type="password" id="confirmPassword" name="confirmPassword" class="custom-input" minlength="6"
                #confirmPassword="ngModel" required ngModel />
        </div>
        <button type="submit" class="custom-btn btn-pink"
            [disabled]="signupForm.touched && signupForm.valid">Signup</button>
    </form>
</section>

<!--
    aria-assertive
    aria-live
-->
