// client/src/components/sign-up/sign-up.component.jsx
import React, { useState } from "react";
import Container from "../container/Container";
import CustomButton from "../custom-button/custom-buttom.component";
import FormInput from "../form-input/form-input.component";
import {
  ButtonsBarContainer,
  SignUpContainer,
  SignUpTitle,
  SignUpTitleContainer,
} from "./sign-up.styles";

const SignUp = () => {
  const [state, setState] = useState({
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    confirmPassword: "",
  });

  const { firstName, lastName, email, password, confirmPassword } = state;
  const handleSubmit = async (event) => {
    event.preventDefault();
    const { email, password } = state;
    console.log(`${email} => ${password}`);
  };
  const handleChange = (event) => {
    const { value, name } = event.target;
    setState({ [name]: value });
  };
  return (
    <Container>
      <SignUpContainer>
        <SignUpTitleContainer>
          <SignUpTitle>Signup</SignUpTitle>
          <span>We do not share your personal details with anyone</span>
        </SignUpTitleContainer>
        <form onSubmit={handleSubmit}>
          <FormInput
            name="firstName"
            type="text"
            handleChange={handleChange}
            value={firstName}
            label="First Name"
            required
            autoComplete="true"
          />
          <FormInput
            name="lastName"
            type="text"
            handleChange={handleChange}
            value={lastName}
            label="Last name"
            required
            autoComplete="true"
          />
          <FormInput
            name="email"
            type="email"
            handleChange={handleChange}
            value={email}
            label="Email"
            required
            autoComplete="true"
          />
          <FormInput
            name="password"
            type="password"
            value={password}
            handleChange={handleChange}
            label="Password"
            required
            autoComplete="true"
          />
          <FormInput
            name="confirmPassword"
            type="password"
            value={confirmPassword}
            handleChange={handleChange}
            label="Confirm Password"
            required
            autoComplete="true"
          />
          <ButtonsBarContainer>
            <CustomButton type="submit"> Sign in </CustomButton>
          </ButtonsBarContainer>
        </form>
      </SignUpContainer>
    </Container>
  );
};

export default SignUp;

// frontend/src/app/auth/components/signup/signup.component.ts
import { Component, ElementRef, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignupComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  onSubmit(signupFormInfo: any) {
    console.log(signupFormInfo.value);
  }

}

<section class="custom-flex-container">
    <article>
        <h2>Signup</h2>
        <p>We do not share your personal details with anyone.</p>
    </article>
    <form class="bazar-signup-form" #signupForm="ngForm" (ngSubmit)="onSubmit(signupForm)">
        <div class="custom-form-group">
            <label for="firstName">First Name</label>
            <input type="text" id="firstName" name="firstName" class="custom-input" required #fname="ngModel" ngModel />
            <div class="custom-error" *ngIf="fname.touched && fname.valid">shsjh</div>
        </div>
        <div class="custom-form-group">
            <label for="lastName">Last Name</label>
            <input type="text" id="lastName" name="lastName" class="custom-input" required #lname="ngModel" ngModel />
        </div>
        <div class="custom-form-group">
            <label for="email">Email</label>
            <input type="email" id="email" name="email" class="custom-input" required #email="ngModel" ngModel />
        </div>
        <div class="custom-form-group">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" class="custom-input" minlength="6" #password="ngModel"
                required ngModel />
        </div>
        <div class="custom-form-group">
            <label for="confirmPassword">Confirm Password</label>
            <input type="password" id="confirmPassword" name="confirmPassword" class="custom-input" minlength="6"
                #confirmPassword="ngModel" required ngModel />
        </div>
        <button type="submit" class="custom-btn btn-pink"
            [disabled]="signupForm.touched && signupForm.valid">Signup</button>
    </form>
</section>

<!--
    aria-assertive
    aria-live
-->
