// client/src/components/login/Login.jsx
import React, { useState } from "react";
import { Button, Form } from "react-bootstrap";
import { useNavigate } from "react-router-dom";
import "./login.css";
const loginFieldInputs = {
  email: "",
  password: "",
};
const Login = () => {
  const navigate = useNavigate();
  const [fieldValue, setFieldValue] = useState(loginFieldInputs);
  const { email, password } = fieldValue;
  const handleLoginChanges = (event) => {
    const { name, value } = event.target;
    setFieldValue({ ...fieldValue, [name]: value });
  };

  const handleLogin = async (event) => {
    event.preventDefault();
    navigate("/home");
  };
  return (
    <div className="auth-container">
      <div className="login-container">
        <h1>Login</h1>
        <p>Get access to your Orders, Wishlist and Recommendations</p>
      </div>
      <div className="login-container">
        <Form onSubmit={handleLogin}>
          <div className="group">
            <label className="form-input-label">Email</label>
            <input
              type="email"
              className="form-input"
              required
              name="email"
              value={email}
              onChange={handleLoginChanges}
            />
          </div>
          <div className="group">
            <label className="form-input-label">Password</label>
            <input
              type="password"
              className="form-input"
              required
              name="password"
              value={password}
              onChange={handleLoginChanges}
              minLength="6"
              pattern="^[a-zA-Z0-9]*$"
            />
          </div>
          <Button className="customSubmit mt-3" size="sm" type="submit">
            Login
          </Button>
        </Form>
      </div>
    </div>
  );
};

export default Login;

// frontend/src/app/features/auth/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  constructor(private readonly router: Router) { }

  ngOnInit(): void {
  }

  onSubmit() {
    this.router.navigate(['/home']);
  }

}

<section class="custom_flex-container">
    <article>
        <h2>Login</h2>
        <p>Get access to your Orders, Wishlist and Recommendations</p>
    </article>
    <form class="custom_login-form" method="POST" #loginForm="ngForm" (ngSubmit)="onSubmit()" novalidate>
        <div class="custom_form-group">
            <label for="email">Email</label>
            <input type="email" id="email" name="email" class="custom_form-input"
                pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required ngModel #email="ngModel"
                aria-describedby="Please enter email here" />
            <div class="custom_form-error-group" *ngIf="email.touched && !email.valid">
                <div *ngIf="email.errors?.required" aria-live="assertive"><i
                        class="fas fa-exclamation-circle"></i>Please enter email.</div>
                <div *ngIf="email.errors?.pattern" aria-live="assertive"><i class="fas fa-exclamation-circle"></i>Please
                    enter email in correct format</div>
            </div>
        </div>
        <div class="custom_form-group">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" class="custom_form-input" required ngModel
                #password="ngModel" pattern="^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$"
                aria-describedby="Please enter password here" />
            <div class="custom_form-error-group" *ngIf="password.touched && !password.valid">
                <div *ngIf="password.errors?.required" aria-live="assertive"><i
                        class="fas fa-exclamation-circle"></i>Please enter password.</div>
                <div *ngIf="password.errors?.minlength" aria-live="assertive"><i
                        class="fas fa-exclamation-circle"></i>Minimum 6 characters required</div>
                <div *ngIf="password.errors?.pattern" aria-live="assertive"><i
                        class="fas fa-exclamation-circle"></i>Please enter alphanumeric password without
                    spaces</div>
            </div>
        </div>
        <button type="submit" class="custom_btn custom_btn--pink" [disabled]="!loginForm.valid">Login</button>
    </form>
</section>
