// ClientSide/src/app/core/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { HomeService } from 'src/app/shared/services/home.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
  constructor(private cartService: HomeService) {}

  ngOnInit(): void {}

  onClickCart() {
    this.cartService.show();
  }
}

<div class="skip">
  <a href="#content">Skip to main content</a>
</div>
<header class="header">
  <div class="logo">
    <img src="static/images/logo_2x.png" sizes="80vw" alt="Sabka Bazaar" aria-label="Home Page" role="button"
      tabindex="0" />
  </div>
  <nav class="nav-center">
    <ul>
      <li>
        <a class="nav-item" routerLink="home" href="javascript: void(0)"> Home </a>
      </li>
      <li>
        <a class="nav-item" routerLink="plp" href="javascript: void(0)"> Products </a>
      </li>
    </ul>
  </nav>
  <div class="nav-right">
    <ul>
      <li>
        <a class="nav-item" routerLink="login" href="javascript: void(0)">
          Sign in
        </a>
      </li>
      <li>
        <a class="nav-item" routerLink="register" href="javascript: void(0)">
          Register
        </a>
      </li>
    </ul>
    <div class="nav-mini-cart">
      <a href="javascript: void(0)" (click)="onClickCart()">
        <img class="cart-logo" src="static/images/cart.svg" alt="Mini cart" aria-label="Your cart items" />
      </a>
      <span>0 items</span>
    </div>
  </div>
</header>

// src/components/Header/Header.tsx
import React from "react";
import logo from "../../static/images/logo.png";
import cart from "../../static/images/cart.svg";
import "./Header.scss";

export const Header = () => {
    return (
        <header className="header">
            
            <div className="header__logo">
                <img src={logo} alt="Sabka Bazaar Logo"/>
            </div>

            <nav className="header__nav">

                <div className="nav--left">
                 <div>Home</div>
                 <div>Products</div>
                </div>

                <div className="nav--right">
                    <div>SignIn</div>
                    <div>Register</div>
                </div>

                <div className="nav--cart">
                    <div className="cart"><img src={cart} alt="cart"/></div>
                    <div>0 items</div>
                </div>

            </nav>
        </header>
    )
}
