// react-seo-friendly-spa-template-master/src/layouts/Footer.tsx
import type { FunctionComponent } from "react";


const Footer: FunctionComponent = () => {

  return (
    <footer className="footer">
      <p className="footer__text">
        Copyright &copy; 2011 - 2018 sabka bazar Grocery supplies Pvt. Ltd
      </p>
    </footer>
  );
}

export default Footer;

// src/app/core/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.sass'],
})
export class FooterComponent {}

<footer class="clearfix copyright padding-10 margin-top-10">
    <app-paragraph [type]="'p-copywrite'"  [desc]="'Copyright &copy; 2011-2018 Sbka Bazar Grocery Supplies Pvt Ltd.'"></app-paragraph>
</footer>
