// src/components/Header/Header.tsx
import React from "react";
import logo from "../../static/images/logo.png";
import cart from "../../static/images/cart.svg";
import "./Header.scss";

export const Header = () => {
    return (
        <header className="header">
            
            <div className="header__logo">
                <img src={logo} alt="Sabka Bazaar Logo"/>
            </div>

            <nav className="header__nav">

                <div className="nav--left">
                 <div>Home</div>
                 <div>Products</div>
                </div>

                <div className="nav--right">
                    <div>SignIn</div>
                    <div>Register</div>
                </div>

                <div className="nav--cart">
                    <div className="cart"><img src={cart} alt="cart"/></div>
                    <div>0 items</div>
                </div>

            </nav>
        </header>
    )
}

// frontend/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable, of } from 'rxjs';
import { DataService } from '../services/data.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.sass']
})
export class HeaderComponent implements OnInit {
  productsLength$: Observable<number> = of(0);

  constructor(readonly dataservice: DataService) {
    this.productsLength$ = this.dataservice.getselectedProdustsLength();
  }

  ngOnInit(): void {
  }

}

<div class="header">
  <img class="logo" src="assets/images/logo.png">
  <ul class="main-nav">
    <li><a routerLink="/home">Home</a></li>
    <li><a routerLink="/products">Products</a></li>
  </ul>
  <div class="user-auth">
    <ul>
      <li><a routerLink="/login">SignIn</a></li>
      <li><a routerLink="/register">Register</a></li>
    </ul>
    <button class="cart-btn">
      <img src="assets/images/cart.svg">
      {{productsLength$ | async}} Items
    </button>
  </div>
</div>
