// app/src/authComponent/signUp.jsx
import React, {  useEffect, useState } from 'react';
import { Col, Form,  Row } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import './form.scss';

const SignUp = () => {
    const initialValue = { firstname: "", lastname: "", email: "", password: "", confirmpassword: "" };
    const [formValues, setFormValues] = useState(initialValue);
    const [errors, setErrors] = useState(false);
    const [isSubmit, setIsSubmit] = useState(false)
    const navigate = useNavigate();
    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormValues({ ...formValues, [name]: value });

    }
    const handleSubmit = (e) => {
        e.preventDefault();
        setErrors(validate(formValues));
        setIsSubmit(true);
    }
    const validate = (values) => {
        const formerrors = {};
        const regx = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i;
        if (!values.firstname) {
            formerrors.firstname = 'Firstname is required';
        }
        if (!values.lastname) {
            formerrors.lastname = 'Lastname is required';
        }
        if (!values.email) {
            formerrors.email = 'Email is required';
        } else if (!regx.test(values.email)) {
            formerrors.email = 'This is not valid email format';
        }
        if (!values.password) {
            formerrors.password = 'Password is required';
        }
        if (!values.confirmpassword) {
            formerrors.confirmpassword = 'Confirm password is required';
        } else if (values.password !== values.confirmpassword) {
            formerrors.confirmpassword = 'Password entered did not match!'
        }
        return formerrors;
    }

    useEffect(() => {
        console.log(errors)
        if (Object.keys(errors).length === 0 && isSubmit) {
            navigate('/')
        }
    }, [errors])

    return (
        <div className='form-sec'>
            <Row className="justify-content-md-center">
                <Col md={6}>
                    <div className='signup-data'>
                        <h3>SignUp</h3>
                        <p>We do not share your personal details with anyone</p>
                    </div>
                </Col>
                <Col md={4}>
                    <Form onSubmit={handleSubmit} >
                        <div className='form-group'>
                            
                            <input type="text" placeholder='First Name' className={errors.firstname ? 'error-border' : ''} name="firstname" value={formValues.firstname} onChange={handleChange} />
                            <p className='error'>{errors.firstname}</p>
                        </div>
                        <div className='form-group'>
                          
                            <input type="text" placeholder='Last Name' className={errors.lastname ? 'error-border' : ''} name="lastname" value={formValues.lastname} onChange={handleChange} />
                            <p className='error'>{errors.lastname}</p>
                        </div>
                        <div className='form-group'>
                           
                            <input type="text" placeholder='Email' className={errors.email ? 'error-border' : ''} name="email" value={formValues.email} onChange={handleChange} />
                            <p className='error'>{errors.email}</p>
                        </div>
                        <div className='form-group'>
                          
                            <input type="password" placeholder='Password' className={errors.password ? 'error-border' : ''} name="password" value={formValues.password} onChange={handleChange} />
                            <p className='error'>{errors.password}</p>
                        </div>
                        <div className='form-group'>
                            
                            <input type="text" placeholder='Confirm password' className={errors.confirmpassword ? 'error-border' : ''} name="confirmpassword" value={formValues.confirmpassword} onChange={handleChange} />
                            <p className='error'>{errors.confirmpassword}</p>
                        </div>
                        <button type="submit" className='btn-cls login-btn'>Signup</button>
                    </Form>
                </Col>
            </Row>
        </div>
    );
}

export default SignUp;

// src/app/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { ValidationService } from './../shared/services/validation.service';
import { Router } from '@angular/router';
import { ISignup } from './../models/ISignup';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignupComponent implements OnInit {
  private errorValues:any;
  public signupForm: ISignup;
  constructor(private _validationService : ValidationService,private router: Router) { }

  ngOnInit() {
    this.signupForm={
      firstname:{
        name:"",
        error:{
          isError: false,
          errorMsg: ""
        }
      },
      lastname:{
        name:"",
        error:{
          isError: false,
          errorMsg: ""
        }
      },
      email:{
        name:"",
        error:{
          isError: false,
          errorMsg: ""
        }
      },
      password:{
        name:"",
        error:{
          isError: false,
          errorMsg: ""
        }
      },
      confirmPassword:{
        name:"",
        error:{
          isError: false,
          errorMsg: ""
        }
      }
    }
    this._validationService.get();
  }
  changedField(fieldValue:any,type:any){
    if(type ==='password'){
     this._validationService.selectedPassword = fieldValue;
    }
    this._validationService.validate(fieldValue,type);
    this.errorValues = this._validationService.validations.filter(obj=> obj.error=== true);
    console.log("Error values =  ",this.errorValues)
    this._validationService.setErrors(this.signupForm,this.errorValues);
    console.log("Forn obj = ",this.signupForm)
  }
  onSubmit(){
    let errors=[];
    let fields = document.querySelectorAll("input");
    for(let i =0;i<fields.length;i++){
      this.changedField(fields[i].value,fields[i].name);
    }

    errors = this._validationService.validations.filter(obj=>obj.error===true);
    if(errors && !errors.length){
      this.router.navigate(['/home']);
    }
  }
}

<main class="login-wrapper margin-top-20">
    <div class="row page-body">
        <div class="col span-1-of-6"></div>
        <!-- Content container for sign up form -->

        <section class="col span-2-of-6 text-center top-pane">
            <header>
                <h1 class="text-left form-heading">Signup</h1>
                <h5 class="text-left form-desc margin-top-20">We do not share your personal details with anyone</h5>
            </header>
        </section>


        <!-- Signup form container -->

        <div class="col span-2-of-6 text-center bottom-pane">
            <form class="login-form">
                <div class="text-left">
                    <label class="font-12" id="nameLbl" tabindex="-1" for="firstname">First Name</label>
                </div>
                <div class="text-left">
                    <input id="firstname" [(ngModel)]="firstname" (ngModelChange)="changedField(firstname,'firstname')"  type="text" aria-required="true" aria-labelledby="nameLbl" name="firstname">
                    <p class="error" *ngFor="let error of errorValues | filterByType: 'firstname'">
                        {{error.errorMsg}}
                    </p>
                </div>
                
                <div class="text-left margin-top-20">
                    <label class="field-label" id="lastnameLbl" tabindex="-2" for="lastname">Last Name</label>
                </div>
                <div class="text-left">
                    <input id="lastname" [(ngModel)]="lastname" (ngModelChange)="changedField(lastname,'lastname')"  type="text" name="lastname" aria-required="true" aria-labelledby="lastnameLbl">
                    <p class="error" *ngFor="let error of errorValues | filterByType: 'lastname'">
                        {{error.errorMsg}}
                    </p>
                </div>
                <div class="text-left margin-top-20">
                    <label class="field-label" tabindex="-3" id="emailLbl" for="email">Email</label>
                </div>
                <div class="text-left">
                    <input id="email" [(ngModel)]="email" (ngModelChange)="changedField(email,'email')" type="email" name="email" aria-required="true" aria-labelledby="emailLbl">
                    <p class="error" *ngFor="let error of errorValues | filterByType: 'email'">
                        {{error.errorMsg}}
                    </p>
                </div>
                
                <div class="text-left margin-top-20">
                    <label class="field-label" id="pwdLbl" tabindex="-4" for="password">Password</label>
                </div>
                <div class="text-left">
                    <input id="password" [(ngModel)]="password" (ngModelChange)="changedField(password,'password')" type="password" name="password" aria-required="true" aria-labelledby="pwdLbl">
                    <p class="error" *ngFor="let error of errorValues | filterByType: 'password'">
                        {{error.errorMsg}}
                    </p>
                </div>

                <div class="text-left margin-top-20">
                    <label class="field-label" tabindex="-5"  id="confPwdLbl" for="confirmPassword">Confirm Password</label>
                </div>
                <div class="text-left">
                    <input id="confirmPassword" [(ngModel)]="confirmPassword" (ngModelChange)="changedField(confirmPassword,'confirmPassword')" type="password" name="confirmPassword" aria-required="true" aria-labelledby="confPwdLbl">
                    <p class="error" *ngFor="let error of errorValues | filterByType: 'confirmPassword'">
                        {{error.errorMsg}}
                    </p>
                </div>
                <button aria-label="Signup Button" (click)="onSubmit()" (keydown.enter)="onSubmit()" class="cursor-pointer block-btn padding-10">Signup</button>
            </form> 
        </div>

        <div class="col span-1-of-6"></div>
    </div> 
</main>
