// src/client/components/Products/ProductItem.jsx
import React from 'react';

const ProductItem = ({ product, addToCart }) => (
  <div className="product-list__item">
    <h1 className="product-list__item--title">{product.name}</h1>
    <div className="product-list__item-description">
      <img className="product-list__item--image" src={product.imageURL} alt={product.description} />
      <div className="product-list__item--info">
        {product.description}
      </div>
      <button
        type="button"
        disabled={product.stock - product.count === 0}
        className="btn m-btn-buy"
        onClick={() => addToCart(product)}
      >
        {`Buy Now @ Rs.${product.price}`}
      </button>
    </div>
    <div className="product-list__item--action">
      <span className="product-list__item--action-mrp">
        {`MRP Rs.${product.price}`}
      </span>
      <button
        type="button"
        disabled={product.stock - product.count === 0}
        className="btn product-list__item--action-buy"
        onClick={() => addToCart(product)}
      >
        Buy Now
      </button>
    </div>
  </div>
);

ProductItem.defaultProps = {
  product: {},
  addToCart: () => {},
};

export default ProductItem;

// src/app/products/product-item/product-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CartService } from 'src/app/services/cart.service';
import { IProduct } from '../models/product.model';

@Component({
  selector: 'app-product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.sass'],
})
export class ProductItemComponent implements OnInit {
  @Input() product!: IProduct;
  constructor(private cartService: CartService) {}

  ngOnInit(): void {}

  addToCart(item: IProduct) {
    this.cartService.addToCart(item);
  }
}

<div class="product">
  <div class="container">
    <div class="title">{{ product.name }}</div>
    <img [src]="'../../assets/' + product.imageURL" />
    <div class="desc">
      <p>{{ product.description }}</p>
    </div>
    <div class="product-footer">
      <div class="price">MRP Rs.{{ product.price }}</div>
      <button (click)="addToCart(product)" class="buy-now">Buy Now</button>
    </div>
  </div>
</div>
