// ClientSide/src/app/core/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { HomeService } from 'src/app/shared/services/home.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
  constructor(private cartService: HomeService) {}

  ngOnInit(): void {}

  onClickCart() {
    this.cartService.show();
  }
}

<div class="skip">
  <a href="#content">Skip to main content</a>
</div>
<header class="header">
  <div class="logo">
    <img src="static/images/logo_2x.png" sizes="80vw" alt="Sabka Bazaar" aria-label="Home Page" role="button"
      tabindex="0" />
  </div>
  <nav class="nav-center">
    <ul>
      <li>
        <a class="nav-item" routerLink="home" href="javascript: void(0)"> Home </a>
      </li>
      <li>
        <a class="nav-item" routerLink="plp" href="javascript: void(0)"> Products </a>
      </li>
    </ul>
  </nav>
  <div class="nav-right">
    <ul>
      <li>
        <a class="nav-item" routerLink="login" href="javascript: void(0)">
          Sign in
        </a>
      </li>
      <li>
        <a class="nav-item" routerLink="register" href="javascript: void(0)">
          Register
        </a>
      </li>
    </ul>
    <div class="nav-mini-cart">
      <a href="javascript: void(0)" (click)="onClickCart()">
        <img class="cart-logo" src="static/images/cart.svg" alt="Mini cart" aria-label="Your cart items" />
      </a>
      <span>0 items</span>
    </div>
  </div>
</header>

// client/src/components/Header/Header.jsx
import React from "react";
import "./Header.scss";
import { Link } from "react-router-dom";
import { ReactComponent as Cart } from "../../assets/images/cart.svg";
import Logo from "../../assets/images/logo_2x.png";
import ApplicationUrls from "../../router/ApplicationRoutes";
import { LABEL } from "../../constants/constant";

export default function Header() {
  return (
    <header>
      <div className="container">
        <div className="logo">
          <img src={Logo} alt="Sabka Bazaar" />
        </div>
        <nav className="navOptions">
          <span>
            <Link to={ApplicationUrls.HOME}>{LABEL.HOME}</Link>
          </span>
          <span>
            <Link to="/products">Products</Link>
          </span>
        </nav>
        <div style={{ position: "absolute", right: "50px" }}>
          <div className={"cartLogoContainer"}>
            <nav className={"text"}>
              <span>
                <Link to={ApplicationUrls.LOGIN}>{LABEL.SIGNIN}</Link>
              </span>

              <span>
                <Link to={ApplicationUrls.REGISTER}>{LABEL.REGISTER}</Link>
              </span>
            </nav>
            <div className={"cartIcon"}>
              <button className="cartbtn">
                <Cart name="cartButton" fill="#e83583" />
              </button>
              <div>0 items</div>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}
