// src/app/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {
  registerForm: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group({
      firstName: ['', [Validators.required, Validators.minLength(4)]],
      lastName: ['', [Validators.required, Validators.minLength(4)]],
      email: ['', [Validators.required]],
      password: ['', [Validators.required]],
      confirmPassword: ['', [Validators.required]]
    }, { validator: this.matchPassword });
  }

  onRegister() {
    localStorage.setItem('registeredUser',JSON.stringify(this.registerForm.value) );
    alert('User registered successfully. Please login');
    this.router.navigate(['auth/signin']);
  }

  matchPassword(abs: AbstractControl): { mismatch: boolean } {
    if (abs.get('password').value !== abs.get('confirmPassword').value) {
      return { mismatch: true };
    }
  }

}

<div class="container my-5">
    <section class="row">
        <div class="col-lg-6">
            <p class="main-heading" aria-level="1" role="heading">Signup</p>
            <p>We do not share your personal details with anyone.</p>
        </div>

        <div class="col-lg-6">
            <form [formGroup]="registerForm" novalidate (ngSubmit)="onRegister()">
                <div class="form-group custom-group">
                    <input type="text" id="firstName" class="form-control" formControlName="firstName" placeholder=""
                        required aria-label="Enter firstName" autocomplete>
                    <label for="firstName" class="floating-label">First Name</label>

                    <div *ngIf="registerForm.controls['firstName'].touched && !registerForm.controls['firstName'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['firstName'].hasError('required')">
                            Please enter first name
                        </div>
                        <div *ngIf="registerForm.controls['firstName'].hasError('minlength')">
                            Please enter atleast 4 characters
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="text" formControlName="lastName" id="lastName" placeholder=""
                        required aria-label="Enter lastname" autocomplete>
                    <label for="lastName" class="floating-label">Last Name</label>

                    <div *ngIf="registerForm.controls['lastName'].touched && !registerForm.controls['lastName'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['lastName'].hasError('required')">
                            Please enter last name
                        </div>
                        <div *ngIf="registerForm.controls['lastName'].hasError('minlength')">
                            Please enter atleast 4 characters
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="email" formControlName="email" id="email" placeholder=""
                        pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required aria-label="Enter email"
                        autocomplete>
                    <label for="email" class="floating-label">Email</label>

                    <div *ngIf="registerForm.controls['email'].touched && !registerForm.controls['email'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['email'].hasError('required')">
                            Please enter a email
                        </div>
                        <div *ngIf="registerForm.controls['email'].hasError('pattern')" aria-live="assertive">
                            Please enter email in correct format
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="password" formControlName="password" id="password" placeholder=""
                        required minlength="6" pattern="^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$"
                        aria-label="Enter password" autocomplete="off">
                    <label for="password" class="floating-label">Password</label>
                    <div *ngIf="registerForm.controls['password'].touched && !registerForm.controls['password'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['password'].hasError('required')">
                            Please enter a password
                        </div>
                        <div *ngIf="registerForm.controls['password'].hasError('pattern')">
                            Password should contain a number and an alphabet without space
                        </div>
                    </div>
                </div>

                <div class="form-group custom-group">
                    <input class="form-control" type="password" formControlName="confirmPassword" id="confirmPassword"
                        placeholder="" required minlength="6" aria-label="Enter confirmPassword" autocomplete="off">
                    <label for="confirmPassword" class="floating-label">Confirm Password</label>
                    <div *ngIf="registerForm.controls['confirmPassword'].touched && !registerForm.controls['confirmPassword'].valid"
                        class="alert alert-danger">
                        <div *ngIf="registerForm.controls['confirmPassword'].hasError('required')">
                            Please re-enter the password
                        </div>
                    </div>
                    <div *ngIf="registerForm.errors?.mismatch" class="alert alert-danger">
                        Password doesn't match
                    </div>
                </div>

                <button type="submit" class="custom-btn common-btn" [disabled]="!registerForm.valid"
                    aria-label="Click Signup" aria-label="Signup">Signup</button>
            </form>
        </div>
    </section>
</div>

// client/src/components/SignInAndRegister/Register.jsx
import { Button, FormControl, TextField } from "@material-ui/core";
import React, { useEffect, useState } from "react";
import { Col, Container, Row } from "reactstrap";
import { makeStyles } from "@material-ui/core/styles";
import "./login.scss";
import { useNavigate } from "react-router-dom";

const useStyles = makeStyles((theme) => ({
  root: {
    "& > *": {
      margin: theme.spacing(1),
      width: "40ch",
    },
  },
}));

const Register = () => {
  const classes = useStyles();
  const navigate = useNavigate();
  const [state, setState] = useState({
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    confirmPassword: "",
    email_error: "",
    password_error: "",
    confirm_password_error: "",
    password_match_error: "",
  });
  const [users, setUsers] = useState([]);

  const changeHandler = (event) => {
    setState({
      ...state,
      [event.target.name]: event.target.value,
    });
  };

  const emailValidationHandler = () => {
    if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(state.email)) {
      setState({
        ...state,
        email_error: "",
      });
    } else {
      setState({
        ...state,
        email_error: "Invalid Email!!",
      });
    }
  };

  const passwordValidationHandler = (value, type) => {
    if (type === "password") {
      if (/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$/.test(value)) {
        setState({
          ...state,
          password_error: "",
        });
      } else {
        setState({
          ...state,
          password_error:
            "Password must be 6 characters long and must contain at least one letter, one numeric digit",
        });
      }
    } else {
      if (/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$/.test(value)) {
        setState({
          ...state,
          confirm_password_error: "",
        });
      } else {
        setState({
          ...state,
          confirm_password_error:
            "Password must be 6 characters long and must contain at least one letter, one numeric digit",
        });
      }
    }
  };

  const submitHandler = (event) => {
    event.preventDefault();
    if (state.password !== state.confirmPassword) {
      setState({
        ...state,
        password_match_error: "Password doesn't match",
      });
    } else {
      let value = {
        firstName: state.firstName,
        lastName: state.lastName,
        email: state.email,
        password: state.password,
      };
      setUsers([...users, value]);

      setState({
        ...state,
        firstName: "",
        lastName: "",
        email: "",
        password: "",
        confirmPassword: "",
        email_error: "",
        password_error: "",
        confirm_password_error: "",
        password_match_error: "",
      });
        navigate("/signin");
    }
  };

  useEffect(() => {
    sessionStorage.setItem("users", JSON.stringify(users));
  }, [users]);

  return (
    <div>
      <Container>
        <div className="login_form">
          <Row>
            <Col md={6}>
              <h4>
                <strong>Signup</strong>
              </h4>
              <p>We do not share your personal details with anyone.</p>
            </Col>

            <Col md={6}>
              <form
                className={classes.root}
                autoComplete="off"
                onSubmit={submitHandler}
              >
                <FormControl>
                  <TextField
                    id="component-firstName"
                    name="firstName"
                    type="text"
                    label="First Name"
                    value={state.firstName}
                    onChange={changeHandler}
                    required
                  />
                </FormControl>

                <FormControl>
                  <TextField
                    id="component-lastName"
                    name="lastName"
                    type="text"
                    label="Last Name"
                    value={state.lastName}
                    onChange={changeHandler}
                    required
                  />
                </FormControl>

                <FormControl>
                  <TextField
                    id="component-email"
                    name="email"
                    type="text"
                    label="Email"
                    value={state.email}
                    onChange={changeHandler}
                    error={state.email_error.length > 0 ? true : false}
                    helperText={state.email_error}
                    onBlur={emailValidationHandler}
                    required
                  />
                </FormControl>

                <FormControl>
                  <TextField
                    id="component-password"
                    name="password"
                    type="password"
                    label="Password"
                    value={state.password}
                    onChange={changeHandler}
                    helperText={state.password_error}
                    error={state.password_error.length > 0 ? true : false}
                    onBlur={(event) =>
                      passwordValidationHandler(
                        event.target.value,
                        event.target.name
                      )
                    }
                    required
                  />
                </FormControl>

                <FormControl>
                  <TextField
                    id="component-confirmPassword"
                    name="confirmPassword"
                    type="password"
                    label="Confirm Password"
                    value={state.confirmPassword}
                    onChange={changeHandler}
                    errorText={state.confirm_password_error}
                    helperText={state.confirm_password_error}
                    error={
                      state.confirm_password_error.length > 0 ? true : false
                    }
                    onBlur={(event) =>
                      passwordValidationHandler(
                        event.target.value,
                        event.target.name
                      )
                    }
                    required
                  />
                </FormControl>
                <p className="text-danger">{state.password_match_error}</p>
                <Button variant="contained" color="primary" type="submit">
                  Submit
                </Button>
              </form>
            </Col>
          </Row>
        </div>
      </Container>
    </div>
  );
};

export default Register;
