// ClientSide/src/app/core/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { HomeService } from 'src/app/shared/services/home.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent implements OnInit {
  constructor(private cartService: HomeService) {}

  ngOnInit(): void {}

  onClickCart() {
    this.cartService.show();
  }
}

<div class="skip">
  <a href="#content">Skip to main content</a>
</div>
<header class="header">
  <div class="logo">
    <img src="static/images/logo_2x.png" sizes="80vw" alt="Sabka Bazaar" aria-label="Home Page" role="button"
      tabindex="0" />
  </div>
  <nav class="nav-center">
    <ul>
      <li>
        <a class="nav-item" routerLink="home" href="javascript: void(0)"> Home </a>
      </li>
      <li>
        <a class="nav-item" routerLink="plp" href="javascript: void(0)"> Products </a>
      </li>
    </ul>
  </nav>
  <div class="nav-right">
    <ul>
      <li>
        <a class="nav-item" routerLink="login" href="javascript: void(0)">
          Sign in
        </a>
      </li>
      <li>
        <a class="nav-item" routerLink="register" href="javascript: void(0)">
          Register
        </a>
      </li>
    </ul>
    <div class="nav-mini-cart">
      <a href="javascript: void(0)" (click)="onClickCart()">
        <img class="cart-logo" src="static/images/cart.svg" alt="Mini cart" aria-label="Your cart items" />
      </a>
      <span>0 items</span>
    </div>
  </div>
</header>

// client/src/components/Layout/Header.tsx
import styles from './layout.module.scss'
import LogoImage from "../../static/images/logo.png"
import CartImage from "../../static/images/cart.svg"

const Logo = () => {
  return (
    <img src={LogoImage} alt="Logo of Sabka Bazaar" />
  )
}
export const Header = () => {
  return (
    <div className={styles.header_container}>
      <header className={styles.header}>
        <Logo />
        <nav className={styles.nav_links}>
          <a href="#">Home</a>
          <a href="#">Products</a>
        </nav>
        <div>
          <div className={styles.right_nav}>
            <nav className={styles.nav_links_auth}>
              <a href="#">SignIn</a>
              <a href="#">Register</a>
            </nav>

            <button>
              <img src={CartImage} alt="" />
              <span>0 items</span>
            </button>
          </div>
        </div>
      </header>
    </div>
  );
}
