// client/src/components/global/Header.tsx
import { Link } from 'react-router-dom';
import useAppStore from '../../utils/store/store';

function Header() {
  const { cart, isLoggedIn, logOut } = useAppStore();

  return (
    <div className="fixed-header">
      <header className="header">
        <Link to="/">
          <img src="/static/images/logo.png" className="logo" alt="Homepage" />
        </Link>
        <nav className="nav">
          <Link to="/">Home</Link>
          <Link to="/products">Products</Link>
        </nav>
        <div className="right">
          {!isLoggedIn && (
            <div className="auth">
              <Link to="/signin">Sign In</Link>
              <Link to="/register">Register</Link>
            </div>
          )}
          {isLoggedIn && (
            <button type="button" className="logout" onClick={logOut}>
              Logout
            </button>
          )}
          <Link to="/cart" type="button" className="cart-icon">
            <img src="/static/images/cart.svg" alt="Cart" />
            <span className="cart-count">{cart.length}</span>
          </Link>
        </div>
      </header>
    </div>
  );
}

export default Header;

// ui/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CartService } from 'src/Shared/services/cart.service';
import { LoginService } from 'src/Shared/services/login.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.sass']
})
export class HeaderComponent implements OnInit {
  isModal: boolean = false;
  noOfItems: number = 0;
  isLoggedIn: boolean = false;
  constructor(private router: Router, private loginService: LoginService, private cartService: CartService) { }

  ngOnInit(): void {
    this.loginService.isLoggedIn.subscribe((response) => {
      this.isLoggedIn = response;
    });
    this.cartService.getCartItem.subscribe((data) => {
      this.noOfItems = data.reduce(
        (previousVal, currentVal) => previousVal + (currentVal.count || 0),
        0
      );
    });
  }
  logOut() {
    this.isLoggedIn = false;
    this.loginService.isLoggedIn.next(false);
    this.router.navigate(['/login']);
  }
  logIn() {
    this.router.navigate(['/login']);
  }
  register() {
    this.router.navigate(['/signup']);
  }

  onClickCart() {
    this.cartService.show();
  }
}

<nav class="wrapper">
  <div class="logo">
    <a routerLink="home"><img src="../../assets/static/images/logo.png" alt="header logo" /></a>
  </div>
  <div class="header-content wrapper">
    <div class="home">
      <a routerLink="/home">Home</a>
    </div>
    <div class="product">
      <a routerLink="/products">Products</a>
    </div>
  </div>
  <div class="header-right">
    <a *ngIf="isLoggedIn" (click)="logOut()">SignOut</a>
    <a *ngIf="!isLoggedIn" (click)="logIn()">SignIn</a>
    <a *ngIf="!isLoggedIn" (click)="register()">Register</a>
    <div *ngIf="isLoggedIn">
      <a id="miniCartBtn" class="cart" (click)="onClickCart()">
        <img src="assets/static/images/cart.svg" alt="cart image" class="cart-btn" />
        <span id="itemsInCart">{{ noOfItems }} items</span>
      </a>
    </div>
  </div>
</nav>
