// client/src/components/products/ProductItem.tsx
import useAppStore from '../../utils/store/store';
import { Product } from '../../utils/types/product';

function ProductItem({ product }: { product: Product }) {
  const { addToCart } = useAppStore();
  return (
    <div className="product-item">
      <h2 className="product-name">{product.name}</h2>
      <div className="product-content-wrapper">
        <div className="product-image">
          <img src={product.imageURL} alt="Product" />
        </div>
        <div className="product-content">
          <div className="product-description">{product.description}</div>
        </div>
      </div>
      <div className="product-actions">
        <div className="product-price">MRP Rs.{product.price}</div>
        <button type="button" className="desktop-button" onClick={() => addToCart(product)}>
          Buy Now
        </button>
        <button type="button" className="responsive-button" onClick={() => addToCart(product)}>
          Buy Now @ Rs.{product.price}
        </button>
      </div>
    </div>
  );
}

export default ProductItem;

// my-cart/src/app/products/product-item/product-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from 'src/app/appState';
import { Product } from 'src/app/model/Products.model';
import * as productActions from './../productions-actions'

@Component({
  selector: 'product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.scss']
})
export class ProductItemComponent implements OnInit {
  @Input() product!: Product;
  constructor(private store:Store<AppState>) { }

  ngOnInit(): void {
  }

  addToCart(){
    this.store.dispatch(new productActions.AddCartItems({...this.product,quantity:1}))
  }

}

<div class="product-item">
    <h3 class="product-item-heading" title="{{product.name}}">{{product.name}}</h3>
    <figure>
        <img class="product-item-image" src="assets{{product.imageURL}}" />
    </figure>
    <p class="product-item-description">{{product.description | ellipsis : 128}}</p>
    <footer class="product-item-footer">
        <div class="footer-desktop">
            <span>MRP Rs.{{product.price}}</span>
            <button class="primary-button buy-now-buttom" (click)="addToCart()">Buy Now</button>
        </div>
        <div class="footer-mobiles">
            <button class="primary-button buy-now-price" (click)="addToCart()">Buy Now @ Rs.{{product.price}}</button>
        </div>
    </footer>
</div>
