// client/src/Components/ProductItem/index.tsx
import { Button } from "../Common"

import { ProductItemProps } from "./models"

import "./styles.scss"

export const ProductItem = ({
  product: { id, name, description, price, imageURL },
}: ProductItemProps) => {
  return (
    <div className="product-item">
      <h4 className="name">{name}</h4>

      <div className="details">
        <img src={imageURL} alt={name} className="image" />

        <div>
          <p className="description">
            {description.substring(0, 150)}
            {description.length > 150 && "..."}
          </p>
          <Button
            type="button"
            variant="primary"
            classes="action-btn-phone"
            handleClick={() => console.log(id)}
          >
            Buy Now @ MRP Rs. {price}
          </Button>
        </div>
      </div>

      <div className="actions flex">
        <span className="price">MRP Rs. {price}</span>

        <Button
          type="button"
          variant="primary"
          classes="action-btn-desktop"
          handleClick={() => console.log(id)}
        >
          Buy Now
        </Button>

        <Button
          type="button"
          variant="primary"
          classes="action-btn-tab"
          handleClick={() => console.log(id)}
        >
          Buy Now @ Rs. {price}
        </Button>
      </div>
    </div>
  )
}

// my-cart/src/app/modules/product/components/product-item/product-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from 'src/app/Store/actions/app.state';
import { Product } from 'src/app/models/products.model';
import * as productActions from '../../../../Store/actions/cart.actions'

@Component({
  selector: 'product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.scss']
})
export class ProductItemComponent implements OnInit {
  @Input() product!: Product;
  constructor(private store: Store<AppState>) { }

  ngOnInit(): void {
  }

  addToCart() {
    this.store.dispatch(new productActions.IncrementCartItemQuantity({ ...this.product, quantity: 1 }))
  }

}

<div class="product-item">
    <h2 class="product-item-heading" title="{{product.name}}">{{product.name}}</h2>
    <img class="product-item-image" src="assets{{product.imageURL}}" alt={{product.description}} />
    <p class="product-item-description">{{product.description | ellipsis : 128}}</p>
    <footer class="product-item-footer">
        <div class="footer-desktop">
            <span>MRP Rs.{{product.price}}</span>
            <button class="primary-button buy-now-buttom" (click)="addToCart()">Buy Now</button>
        </div>
        <div class="footer-mobiles">
            <button class="primary-button buy-now-price" (click)="addToCart()">Buy Now @ Rs.{{product.price}}</button>
        </div>
    </footer>
</div>
