// client/sabka-bazaar/src/components/productItems/productItem.jsx
import Button from '@material-ui/core/Button';
import kiwi from '../../assets/images/products/fruit-n-veg/kiwi-green.jpg'
import './productItem.scss'
const ProductItem=({item})=>{
    return <div className='product-item d-flex flex-column'>
        <h1 className='heading'>{item?.name} </h1>
        <img src={item.imageURL} alt="kiwi" width='220' />
        <span className='des'>{item?.description}</span>
  <div className='d-flex flex-row justify-content-between'><span>MRP Rs.{item.price}</span>       <Button className='buy-button' variant="contained">Buy Now</Button>
</div>
    </div>
}
export default ProductItem;

// my-cart/src/app/modules/product/components/product-item/product-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from 'src/app/Store/actions/app.state';
import { Product } from 'src/app/models/products.model';
import * as productActions from '../../../../Store/actions/cart.actions'

@Component({
  selector: 'product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.scss']
})
export class ProductItemComponent implements OnInit {
  @Input() product!: Product;
  constructor(private store: Store<AppState>) { }

  ngOnInit(): void {
  }

  addToCart() {
    this.store.dispatch(new productActions.IncrementCartItemQuantity({ ...this.product, quantity: 1 }))
  }

}

<div class="product-item">
    <h2 class="product-item-heading" title="{{product.name}}">{{product.name}}</h2>
    <img class="product-item-image" src="assets{{product.imageURL}}" alt={{product.description}} />
    <p class="product-item-description">{{product.description | ellipsis : 128}}</p>
    <footer class="product-item-footer">
        <div class="footer-desktop">
            <span>MRP Rs.{{product.price}}</span>
            <button class="primary-button buy-now-buttom" (click)="addToCart()">Buy Now</button>
        </div>
        <div class="footer-mobiles">
            <button class="primary-button buy-now-price" (click)="addToCart()">Buy Now @ Rs.{{product.price}}</button>
        </div>
    </footer>
</div>
