// client/src/components/Signin/Register.jsx
import React, { Fragment } from 'react';
import { useHistory } from 'react-router-dom';
import './signin.css';

function Register() {

    const history = useHistory()

    function register() {
        history.push('/category/all')
    }

    return (
        <Fragment>
            <div className="signin">
                <div className="signin--panel">
                    <span className="login-text">SignUp</span>
                    <span className="login-subheader">We do not share your personal details with anyone.</span>
                </div>

                <div className="signin-form">
                    <form className="signin-form">
                        <div className="input-group">
                            <input type="text" required />
                            <span className="highlight"></span>
                            <span className="bar"></span>
                            <label>FirstName</label>
                        </div>

                        <div className="input-group">
                            <input type="password" required />
                            <span className="highlight"></span>
                            <span className="bar"></span>
                            <label>LastName</label>
                        </div>

                        <div className="input-group">
                            <input type="text" required />
                            <span className="highlight"></span>
                            <span className="bar"></span>
                            <label>Email</label>
                        </div>

                        <div className="input-group">
                            <input type="password" required />
                            <span className="highlight"></span>
                            <span className="bar"></span>
                            <label>Password</label>
                        </div>

                        <div className="input-group">
                            <input type="text" required />
                            <span className="highlight"></span>
                            <span className="bar"></span>
                            <label>Confirm Password</label>
                        </div>

                        <button className="login-btn" onClick={() => register()}>Register</button>
                    </form>
                </div>
            </div>



            <div className="copyright">
                <p className="copyright-text">Copyright &#169; 2011-1018 Sabka Bazaar Grocery Supplies Pvt Ltd</p>
            </div>
        </Fragment>

    )
}

export default Register;

// frontend/src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.sass']
})
export class RegisterComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="details">
  <h1>SignUp</h1>
  <p>We do not share your personal details with anyone.</p>
</div>
<form class="register-form">
  <mat-form-field>
    <mat-label>First Name</mat-label>
    <input matInput>
  </mat-form-field>
  <mat-form-field>
    <mat-label>Last Name</mat-label>
    <input matInput>
  </mat-form-field>
  <mat-form-field>
    <mat-label>Email</mat-label>
    <input matInput>
  </mat-form-field>
  <mat-form-field>
    <mat-label>Password</mat-label>
    <input matInput type="password">
  </mat-form-field>
  <mat-form-field>
    <mat-label>Confirm Password</mat-label>
    <input matInput type="password">
  </mat-form-field>
  <button class="submit">SignUp</button>
</form>
